src/main/java/bio/terra/cli/auth/AuthenticationManager.java
Always set the pet SA credentials variable on the user, even when the file already exists. This comes up only for the notebooks create, which actually tries to read the pet SA value and gets NPE otherwise.
Before this PR, if the pet SA file existed, `terraUser.petSACredentials` would not be set, causing a NPE on `notebooks create`
https://github.com/DataBiosphere/terra-cli/blob/99ed450a55f8d9f5d8d212e91e2ea1b8934c90ea/src/main/java/bio/terra/cli/command/notebooks/Create.java#L86
=> [no ticket] Always set the pet SA credentials variable on the user

build.gradle, src/main/java/bio/terra/cli/context/WorkspaceContext.java, src/main/java/bio/terra/cli/service/utils/WorkspaceManagerService.java
GOOGLE -> GCP renaming in WSM codebase.
=> PF-572: Bump WSM client library version, update changed methods.

CONTRIBUTING.md, README.md
- Updated the README with the reorganized `terra resources` group of commands.
- Also did a pass through both README and CONTRIBUTING updating wording and fixing paragraph structure.
=> PF-727: Update readme with resources changes

CONTRIBUTING.md, README.md
- Updated README with recent command changes.
- Updated CONTRIBUTING with recent package structure changes.
This change is motivated by Nicole noticing the README was out of date when she most recently tested the CLI.
=> PF-833: Update README.

src/main/resources/servers/all-servers.json, src/main/resources/servers/zloery-dev.json
Server config for my personal development env
=> [No ticket] Add dev environment for zloery

src/main/resources/servers/all-servers.json, src/main/resources/servers/terra-verily-autopush.json, src/main/resources/servers/terra-verily-dev.json, src/main/resources/servers/terra-verily-devel.json, src/main/resources/servers/terra-verily-staging.json, src/test/java/unit/Config.java, src/test/java/unit/Server.java
Update URLs and default WSM spend profile.
=> PF-993: Add server definitions for Verily devel and staging. Update autopush.

src/main/java/bio/terra/cli/service/WorkspaceManagerService.java
The `createFailsWithoutSpendAccess` test is failing because of a recent WSM change (PF-556). Now when a user doesn't have spend profile access, we get a job failed instead of an error on the job submission.
The CLI code has a specific check for this error in order to present a more user-friendly error message than "job failed...". This PR updates this CLI check to look for a job failure instead of an exception on job submission.
Note: This test is currently failing only on the `broad-dev` environment because that's the only place where the WSM change is live. We'll need to update the `verily-devel` environment also once this CLI change goes in, so that nightly tests will pass on both environments.
=> PF-1179: Update spend profile error handling to check for job failure.

build.gradle, src/main/java/bio/terra/cli/businessobject/Resource.java, src/main/java/bio/terra/cli/businessobject/resource/BqDataTable.java, src/main/java/bio/terra/cli/businessobject/resource/BqDataset.java, src/main/java/bio/terra/cli/businessobject/resource/ResolveOptions.java, src/main/java/bio/terra/cli/command/resource/AddRef.java, src/main/java/bio/terra/cli/command/resource/Resolve.java, src/main/java/bio/terra/cli/command/resource/Update.java, src/main/java/bio/terra/cli/command/resource/addref/BqDataTable.java, src/main/java/bio/terra/cli/command/resource/addref/BqDataset.java, src/main/java/bio/terra/cli/command/resource/update/BqDataTable.java, src/main/java/bio/terra/cli/command/shared/options/BigQueryIds.java, src/main/java/bio/terra/cli/serialization/persisted/resource/PDBqDataTable.java, src/main/java/bio/terra/cli/serialization/userfacing/UFResource.java, src/main/java/bio/terra/cli/serialization/userfacing/input/CreateBqDataTableParams.java, src/main/java/bio/terra/cli/serialization/userfacing/resource/UFBqDataTable.java, src/main/java/bio/terra/cli/service/GoogleBigQuery.java, src/main/java/bio/terra/cli/service/WorkspaceManagerService.java, src/test/java/harness/utils/ExternalBQDatasets.java, src/test/java/unit/BqDataTableReferenced.java, src/test/java/unit/BqDatasetControlled.java, src/test/java/unit/BqDatasetReferenced.java
- Add CLI command for creating, updating, deleting BQ data table reference
=> PF-1171: Add CLI command for BQ data table reference

src/main/java/bio/terra/cli/utils/Logger.java
Greg - I saw you're doing stuff with logs also. I can assign PR-1096 to you after this PR goes in...
Before this PR:
```
11:33:45.908 [main] INFO  bio.terra.cli.businessobject.TerraUser - Found user in SAM: class UserStatus {
```
After this PR:
```
2021-12-09 10:51:20.021 PST [main] INFO  bio.terra.cli.businessobject.TerraUser - Found user in SAM: class UserStatus {
```
=> PF-1096: Add date and timezone to logs

.github/workflows/cleanup-test-user-workspaces.yml, build.gradle
Passing run:
https://github.com/DataBiosphere/terra-cli/actions/runs/1834433205
=> [PR-1289] Fix Cleanup workspace action after #194

README.md
Add installation details or applications callable by `terra`.
=> [PF-1317] local tools installation instructions

README.md, docker/Dockerfile, src/main/java/bio/terra/cli/command/Main.java, src/main/java/bio/terra/cli/command/app/List.java, src/main/java/bio/terra/cli/command/app/passthrough/Git.java, src/test/java/unit/PassthroughApps.java
https://docs.google.com/document/d/14sn6ValS3Mtq9HDlYmUioJ3RzpDRLwsp5Yfby63JVKE/edit?usp=sharing
=> PF-1352: Add git as a passthrough app

src/main/java/bio/terra/cli/businessobject/User.java
User should stays in the same log-in mode in the follow-on command after they log in.
=> [PF-1333]: Fix bug when the log-in mode get lost in the follow-on command

src/main/java/bio/terra/cli/command/Status.java, src/main/java/bio/terra/cli/command/app/passthrough/Git.java, src/main/java/bio/terra/cli/command/auth/Revoke.java, src/main/java/bio/terra/cli/command/auth/Status.java, src/main/java/bio/terra/cli/command/config/set/AppLaunch.java, src/main/java/bio/terra/cli/command/config/set/Image.java
We don't want warning text to show up in stdout, especially when in JSON format mode.
=> [PF-1163] stderr for warnings and error messages

src/test/java/unit/GcpNotebookControlled.java, src/test/java/unit/WorkspaceOverride.java
Example failure:
https://scans.gradle.com/s/o5r6kcpudawae/tests/:runTestsWithTag/unit.WorkspaceOverride/notebooks()?top-execution=1
=> Fix failing notebook tests

src/main/java/bio/terra/cli/command/resource/create/GcpNotebook.java
=> PF-1409: EMPTY_MAP to emptyMap()

.github/workflows/release-on-pr-merge.yml
Passing run:
https://github.com/DataBiosphere/terra-cli/actions/runs/2303241666
=> Really fix bumper action

src/test/java/harness/CRLJanitor.java
#246 introduced a bug which causes the CLI to fail if Janitor is not enabled, sorry about that!
=> [PF-886] Don't initialize janitor pubsub if disabled

README.md, src/main/java/bio/terra/cli/businessobject/Workspace.java, src/main/java/bio/terra/cli/command/shared/options/WorkspaceNameAndDescription.java, src/main/java/bio/terra/cli/command/workspace/Clone.java, src/main/java/bio/terra/cli/command/workspace/Create.java, src/main/java/bio/terra/cli/command/workspace/List.java, src/main/java/bio/terra/cli/command/workspace/Set.java, src/main/java/bio/terra/cli/command/workspace/Update.java, src/main/java/bio/terra/cli/service/WorkspaceManagerService.java, src/test/java/harness/utils/WorkspaceUtils.java, src/test/java/unit/Workspace.java, src/test/resources/testscripts/CreateWorkspace.sh
This PR will be merged after #238. (#238 won't be merged for a while.)
This PR creates `WorkspaceUtils.createWorkspace()`. #246 also creates `WorkspaceUtils.createWorkspace()`. This PR will be simpler after #246 is merged.
Manual testing:
```
~/terra-cli (mc/set-ufid-create): terra workspace create
Missing required option: '--id=<id>'
Usage: terra workspace create [--description=<description>] [--format=<format>]
--id=<id> [--name=<displayName>]
Create a new workspace.
--description=<description>
Workspace description.
--format=<format>      Set the format for printing command output: JSON,
TEXT. Defaults to the config format property.
Default: null
--id=<id>              Workspace id.
--name=<displayName>   Workspace display name (not unique).
~/terra-cli (mc/set-ufid-create): terra …
```
=> [PF-1579] Require `userFacingId` when creating workspace

src/main/java/bio/terra/cli/command/Status.java, src/main/java/bio/terra/cli/serialization/userfacing/UFWorkspace.java, src/main/java/bio/terra/cli/serialization/userfacing/UFWorkspaceLight.java, src/test/java/unit/Workspace.java
=> PF-1631: terra status format more readable

src/main/java/bio/terra/cli/businessobject/Workspace.java, src/main/java/bio/terra/cli/command/shared/options/WorkspaceOverride.java, src/main/java/bio/terra/cli/command/workspace/Clone.java, src/main/java/bio/terra/cli/command/workspace/Update.java, src/main/java/bio/terra/cli/service/WorkspaceManagerService.java, src/test/java/unit/CloneWorkspace.java, src/test/java/unit/Workspace.java
workspace update and clone lake of ufid
workspace update and clone successfully with ufid
=> PF-1621 ufid in workspace update and clone

src/main/java/bio/terra/cli/command/group/List.java, src/test/java/unit/Group.java
=> PF1630: terra group list shows in table view with the test on 2 groups

src/main/java/bio/terra/cli/command/resource/update/GcpNotebook.java, src/main/java/bio/terra/cli/serialization/userfacing/resource/UFGcpNotebook.java, src/test/java/unit/GcpNotebookControlled.java
update one metadata
add multiple entries of metadata.
=> PF-1728: add the metadata display in the text/json

build.gradle, src/main/java/bio/terra/cli/businessobject/Resource.java, src/main/java/bio/terra/cli/serialization/persisted/PDResource.java, src/main/java/bio/terra/cli/serialization/userfacing/UFResource.java
Update the CLI to send a single role with the PrivateResourceUser rather than a list of roles.
=> PF-1218: Send single role for PrivateResourceUser

src/main/java/bio/terra/cli/command/shared/options/ResourceName.java
=> Fix help messages for `terra resource create` --name

src/test/java/unit/GcpNotebookControlled.java, src/test/java/unit/WorkspaceOverride.java
notebook on create get stuck in provisioning. it's not a CLI bug. Disabling the test temporarily until the root issue is resolved.
=> PF-2060: disable notebook test temporarily

src/main/resources/servers/all-servers.json, src/main/resources/servers/verily-mc-dev.json, src/main/resources/servers/verily-mc-flagged.json
Add new verily environments - mc-dev and mc-flagged
=> [PF-2167] Add new verily environments

src/main/java/bio/terra/cli/command/shared/WsmBaseCommand.java
Local testing:
```
yuhuyoyo-macbookpro3% terra workspace list                                                    
ID                                        NAME                            GOOGLE PROJECT                  DESCRIPTION                             
hellowworld                               (unset)                         terra-vdevel-fast-pecan-4912    (unset)                                 
newworkspace                              (unset)                         terra-vdevel-slick-celery-4195  (unset)                                 
1000-genomes                              1000 Genomes Phase 3            terra-vdevel-arctic-plum-2597   ## How to run notebook using 1000 Gen...
buoyant-plum                              Melissa researcher workspace …
```
=> PF-2304: set logging in WsmBaseCommand

.github/workflows/cleanup-test-user-workspaces.yml, .github/workflows/release-on-pr-merge.yml, .github/workflows/tests-nightly.yml, .github/workflows/tests-on-pr-push-and-merge.yml, .github/workflows/update-gradle-version.yml
I've been staring at GHA results for a couple days and figured we should probably fix the warnings about deprecated actions.
=> [PF-2351] Fix GHA warnings

gradle/test.gradle
Clean PR from https://github.com/DataBiosphere/terra-cli/pull/422
=> Support running tests by single tag

.github/workflows/release-on-pr-merge.yml, CONTRIBUTING.md, settings.gradle, tools/publish-release.sh
Fix build number in settings.gradle - error caused due to intermediate PR merged
=> Fix build number in settings.gradle

src/main/resources/servers/verily-preprod.json
merge after https://github.com/verily-src/terra-internal-modules/pull/19
=> [BENCH-636] Enable AWS on preprod

.github/workflows/release-on-pr-merge.yml, settings.gradle
Remove \ since this seems to be not handled correctly
=> Remove \ in GH workflow

.github/workflows/release-on-pr-merge.yml, settings.gradle, tools/client-credentials.sh, tools/render-config.sh
disable pipefail option since it wrongly returns script exit code as error
=> disable pipefail

README.md, src/main/java/bio/terra/cli/utils/CommandUtils.java
=> Correctly print cloud platform value instead of object reference

README.md
Doc update for - https://github.com/DataBiosphere/terra-cli/pull/525
=> [BENCH-863] Doc update - override default spend profile

src/main/java/bio/terra/cli/service/FeatureService.java
@rogerwangcs might want to consider passing in the user email if we want to have some user to have early access to dataproc in prod.
=> Enable checking email address

src/main/java/bio/terra/cli/utils/CommandUtils.java
https://verily.atlassian.net/browse/BENCH-1067
=> BENCH-1067: Flip dataproc flag check

README.md, settings.gradle, src/main/java/bio/terra/cli/businessobject/Workspace.java, src/main/java/bio/terra/cli/command/Resource.java, src/main/java/bio/terra/cli/command/resource/ListTree.java, src/main/java/bio/terra/cli/command/resource/MoveToFolder.java, src/main/java/bio/terra/cli/command/shared/options/FolderId.java, src/main/java/bio/terra/cli/service/WorkspaceManagerService.java
tera resource move --name=resource --folder-id=id
=> BENCH-980: add command terra resource move

src/main/java/bio/terra/cli/command/workspace/ConfigureAws.java, src/main/java/bio/terra/cli/utils/AwsConfiguration.java, src/test/java/unit/WorkspaceAwsTest.java
with append option - only overwrite config options that are provided
default behavior - overwrite all config options
=> [BENCH-1098] Add append option to aws-configure
