DataBiosphere/terra-cli

build.gradle, src/main/java/bio/terra/cli/command/Notebooks.java, src/main/java/bio/terra/cli/utils/WorkspaceManagerUtils.java
Updated the "terra workspace create" command to call the new WSM endpoints for creating a cloud context and polling for job completion.
Note: This change is required for the "terra workspace create" command to work again. WSM has already updated their (dev) server, so the CLI is broken until this fix goes in.
=> PF-439: Update create workspace to use latest WSM client library.

src/main/java/bio/terra/cli/command/Notebooks.java, src/main/java/bio/terra/cli/command/notebooks/Create.java, src/main/java/bio/terra/cli/command/notebooks/Describe.java, src/main/java/bio/terra/cli/command/notebooks/List.java, src/main/java/bio/terra/cli/command/notebooks/Start.java, src/main/java/bio/terra/cli/command/notebooks/Stop.java
Longer term, I expect the describe and list commands to talk to the Notebooks Service. As-is, no formatting is undertaken, but I'd like to get these commands in for an initial semi-usable milestone to pass off to Solutions folks.
Also tweak location description in other commands.
=> PF-339 Add describe, list, start, and stop initial notebooks commands.

CONTRIBUTING.md, README.md, src/main/java/bio/terra/cli/service/ServerManager.java
Temporarily changed the default server from `terra-dev` to `wchamber-dev`, because the Terra dev services are behind a firewall that requires users to be on the Broad VPN. There is an open ticket with Broad DevOps to address this. In the meantime, personal development deployments are apparently not behind the firewall, so we're using one of those as a temporary workaround.
Added documentation from today's meeting with Willy/Will/Mariko to get Willy started on adding dsub to the CLI.
=> PF-449: Change default server to wchamber-dev, update documentation.

README.md, build.gradle, docker/Dockerfile, docker/scripts/terra_init.sh, src/main/java/bio/terra/cli/apps/DockerAppsRunner.java, src/main/java/bio/terra/cli/apps/Nextflow.java, src/main/java/bio/terra/cli/command/App.java, src/main/java/bio/terra/cli/command/Auth.java, src/main/java/bio/terra/cli/command/Main.java, src/main/java/bio/terra/cli/command/Notebooks.java, src/main/java/bio/terra/cli/command/Resources.java, src/main/java/bio/terra/cli/command/Server.java, src/main/java/bio/terra/cli/command/Workspace.java, src/main/java/bio/terra/cli/command/resources/Create.java, src/main/java/bio/terra/cli/command/resources/Delete.java, src/main/java/bio/terra/cli/command/resources/Describe.java, src/main/java/bio/terra/cli/command/resources/List.java, src/main/java/bio/terra/cli/context/CloudResource.java, src/main/java/bio/terra/cli/context/WorkspaceContext.java, src/main/java/bio/terra/cli/service/WorkspaceManager.java, src/main/java/bio/terra/cli/service/utils/GoogleCloudStorage.java
1. Resources commands
- First pass at code structure to persist cloud resources and data references on disk only. (This will later have to be changed to use the WSM endpoints, when they are ready.)
- Call GCS directly to create bucket resource.  For this ticket, handle only GCS buckets in the workspace.
2. Resources references
- Pass in resolved resource references to Docker container as environment variables.
- Allow specifying the resource references in the command (e.g. nextflow run -work-dir {TERRA_MY_BUCKET}
3. Nextflow
- Updated Nextflow install in Dockerfile to set the mode for Google Life Sciences.
=> PF-340 Resource commands. Pass in resolved references to Docker container.

src/main/java/bio/terra/cli/service/ServerManager.java
Change back from wchamber-dev now that VPN access is no longer required for accessing terra-dev.
=> PF-474: Change default server back to terra-dev.

README.md, src/main/java/bio/terra/cli/command/Groups.java, src/main/java/bio/terra/cli/command/Main.java, src/main/java/bio/terra/cli/command/Spend.java, src/main/java/bio/terra/cli/command/groups/AddUser.java, src/main/java/bio/terra/cli/command/groups/Create.java, src/main/java/bio/terra/cli/command/groups/Delete.java, src/main/java/bio/terra/cli/command/groups/Describe.java, src/main/java/bio/terra/cli/command/groups/List.java, src/main/java/bio/terra/cli/command/groups/ListUsers.java, src/main/java/bio/terra/cli/command/groups/RemoveUser.java, src/main/java/bio/terra/cli/command/spend/Disable.java, src/main/java/bio/terra/cli/command/spend/Enable.java, src/main/java/bio/terra/cli/command/spend/ListUsers.java, src/main/java/bio/terra/cli/command/workspace/AddUser.java, src/main/java/bio/terra/cli/command/workspace/RemoveUser.java, src/main/java/bio/terra/cli/service/utils/SamService.java, src/main/java/bio/terra/cli/service/utils/SpendProfileManagerService.java
- Added `terra groups` commands for managing SAM groups
- Added `terra spend` commands for managing access to the WSM spend profile.
- Updated README with instructions for granting access to the spend profile, with a preference for adding new users to a group I created called `enterprise-pilot-testers`.
=> PF-452: Groups and Spend commands.

README.md, src/main/java/bio/terra/cli/apps/DockerAppsRunner.java, src/main/java/bio/terra/cli/service/WorkspaceManager.java
- Added a section in the README about workspace context for applications and how to use references.
- Removed manual environment variable substitution. For now we'll just escape the environment variable to bypass the host machine.
(If that syntax turns out to be too clunky, we can add this back later and make it less error-prone. For now, better to have it working reliably, especially since we're still not exactly sure about how invoking applications will look post solutions team + others feedback.)
=> PF-459: Remove manual environment variable substitution.

.gitignore, CONTRIBUTING.md, build.gradle, gradle.properties, src/main/java/bio/terra/cli/apps/DockerAppsRunner.java, tools/build-docker.sh, tools/local-dev.sh, tools/publish-docker.sh
1. Added scripts for building and publishing a Docker image.
2. Added Gradle tasks that wrap those scripts and direct Docker commands: pullDockerImage, buildDockerImage, publishDockerImage.
3. Added instructions for building, pulling, publishing and updating the default image.
4. Changed the `tools/local-dev.sh` script to pull the default image from GCR instead of building it locally.
This is a temporary stand-in for an actual release process. But once we have GH actions or some automated way to do releases, we can have it call these scripts/tasks.
The main purpose of this PR is to un-block Nicole, who was having problems building the image locally on a Cloud Remote Desktop. The goal for this is to have CLI testers just run `source tools/local-dev.sh` and not have to build the Docker …
=> PF-399: Gradle tasks for pull, build, publish Docker image.

src/main/java/bio/terra/cli/apps/DockerAppsRunner.java, src/main/java/bio/terra/cli/auth/AuthenticationManager.java, src/main/java/bio/terra/cli/context/GlobalContext.java, src/main/java/bio/terra/cli/context/TerraUser.java, src/main/java/bio/terra/cli/service/ServerManager.java
1. pet SA key file path = [global context dir]/pet-keys/[user id]/[workspace id]
* Each user now has a sub-directory of the global context directory for their pet SA key files.
* Each pet SA key file is named for the workspace that it belongs to.
* Only the user-specific sub-directory is mounted to the Docker image when running app commands. Previously, the entire pet-keys directory was mounted. The GOOGLE_APPLICATION_CREDENTIALS environment variable is still pointed to the pet SA key file for the current workspace.
2. Added existence checks to AuthenticationManager.loginTerraUser().
* Skip the SAM fetches if the user information is already populated.
* Only update the global context persisted on disk if the user has changed.
If you have a previous installation of the CLI, you'll need to …
=> PF-484: Store multiple pet SA key files per user.

README.md, src/main/java/bio/terra/cli/auth/AuthenticationManager.java, src/main/java/bio/terra/cli/auth/GoogleCredentialUtils.java, src/main/java/bio/terra/cli/command/Auth.java, src/main/java/bio/terra/cli/command/auth/GetBrowser.java, src/main/java/bio/terra/cli/command/auth/SetBrowser.java, src/main/java/bio/terra/cli/context/GlobalContext.java
- Added a boolean flag to the global context for the OAuth login flow.
- true/auto = launch the browser window automatically and listen on a local port for the token response
- false/manual = print the url to stdout, expect the user to open that url in a browser on any machine and copy/paste the token response to stdin
- default = true/auto, which matches the existing behavior
- Added two new commands to manipulate this flag: `terra auth set-browser`, `terra auth get-browser`.
The purpose of this flag is to support logging in on a machine (e.g. CloudShell, notebook VM) that does not have a default (or any) browser available to it. Setting the flag to false/manual means the user can copy the url into a browser on a different machine (e.g. their laptop), confirm the scopes and get the token …
=> PF-445: Add flag for launching browser automatically or not.

README.md, src/main/java/bio/terra/cli/command/notebooks/Create.java, src/main/java/bio/terra/cli/command/notebooks/Delete.java, src/main/java/bio/terra/cli/command/notebooks/Describe.java, src/main/java/bio/terra/cli/command/notebooks/List.java, src/main/java/bio/terra/cli/command/notebooks/Start.java, src/main/java/bio/terra/cli/command/notebooks/Stop.java
This will make the notebooks commands consistent with the other commands, which should help usability.
=> Add '--' prefixes to option parameters of notebooks commands.

CONTRIBUTING.md, README.md, docker/scripts/terra_init.sh, gradle.properties, src/main/java/bio/terra/cli/apps/DockerAppsRunner.java, src/main/java/bio/terra/cli/command/app/SetImage.java, src/main/java/bio/terra/cli/service/WorkspaceManager.java, tools/local-dev.sh, tools/publish-docker.sh
- Changed the name of the environment variable that we use to store the workspace project id, from `TERRA_GOOGLE_PROJECT_ID` -> `GOOGLE_CLOUD_PROJECT`. This new environment variable overrides the project specified in the `nextflow.config` file and is also documented in the Google Cloud Java client library [README](https://github.com/googleapis/google-cloud-java/blob/master/README.md#specifying-a-project-id), so it seems like the better choice here (similar to how GOOGLE_APPLICATION_CREDENTIALS is recognized by different apps).
- Published a new Docker image and bumped the default version used by the CLI.
- Updated the instructions for publishing a new Docker image to include authentication. (I think I didn't need to do this before because I happened to be logged in with a user that had …
=> PF-421: Change project id env var to GOOGLE_CLOUD_PROJECT.

src/main/java/bio/terra/cli/service/ServerManager.java, src/main/java/bio/terra/cli/service/WorkspaceManager.java, src/main/java/bio/terra/cli/service/utils/DataRepoService.java, src/main/java/bio/terra/cli/service/utils/SamService.java, src/main/java/bio/terra/cli/service/utils/WorkspaceManagerService.java
- Propagate exceptions thrown by the Workspace Manager client up to the caller. Previously, they were logged by otherwise failed silently.
- The only exception to this error propagation are calls to the `/status` endpoint, where an exception is interpreted by the CLI the same as a bad status.
- If `terra workspace add-user` fails with a bad request (i.e. code=400), then try to invite them first and then add them to the workspace.
In the future, this invite behavior might be better placed in WSM -- I'm not sure of that, but I've put it on the list of possible requests of WSM from the CLI.
=> PF-508: Invite user if workspace add-user returns bad request.

src/main/java/bio/terra/cli/apps/DockerAppsRunner.java, src/main/java/bio/terra/cli/apps/Nextflow.java, src/main/java/bio/terra/cli/auth/AuthenticationManager.java, src/main/java/bio/terra/cli/command/notebooks/Create.java, src/main/java/bio/terra/cli/command/notebooks/Delete.java, src/main/java/bio/terra/cli/command/notebooks/Describe.java, src/main/java/bio/terra/cli/command/notebooks/List.java, src/main/java/bio/terra/cli/command/notebooks/Start.java, src/main/java/bio/terra/cli/command/notebooks/Stop.java, src/main/java/bio/terra/cli/context/GlobalContext.java, src/main/java/bio/terra/cli/context/WorkspaceContext.java, src/main/java/bio/terra/cli/context/utils/FileUtils.java
- Recursively search the current directory hierarchy for the workspace context file.
- Preserve the current directory, relative to the workspace directory, when running in the container.
- Cleanup the file and directory helper methods for handling the global context and workspace.
- Mount the global context directory and the workspace directory onto the Docker container.
The main goal for these changes is to use any `terra` commands, including those that start a Docker container, in sub-directories of the workspace directory. Previously, you could only use `terra` commands in the top-level workspace directory -- changing to a sub-directory would fail to find the workspace context.
```
> terra workspace create
Workspace successfully created: 03935501-8978-4188-a58a-3fb3d876fd35
> git clone …
```
=> PF-427 Search parent directories for context file. Preserve relative path when running in container.

src/main/java/bio/terra/cli/command/notebooks/Create.java, src/main/java/bio/terra/cli/command/notebooks/Delete.java, src/main/java/bio/terra/cli/command/notebooks/Describe.java, src/main/java/bio/terra/cli/command/notebooks/List.java, src/main/java/bio/terra/cli/command/notebooks/Start.java, src/main/java/bio/terra/cli/command/notebooks/Stop.java
Per solutions team, the r experimental image that has Java installed is a better default choice.
Later we can look at finding an image that isn't experimental, but this image at least will allow installation of the terra CLI out of the box on the notebook instance.
Add `showDefaultValues` to all notebooks commands.
=> PF-527 Change the notebooks default image family

.gitignore, README.md, src/main/java/bio/terra/cli/auth/AuthenticationManager.java, src/main/java/bio/terra/cli/command/DataRefs.java, src/main/java/bio/terra/cli/command/Main.java, src/main/java/bio/terra/cli/command/auth/Status.java, src/main/java/bio/terra/cli/command/datarefs/Add.java, src/main/java/bio/terra/cli/command/datarefs/CheckAccess.java, src/main/java/bio/terra/cli/command/datarefs/Delete.java, src/main/java/bio/terra/cli/command/datarefs/List.java, src/main/java/bio/terra/cli/command/datarefs/Resolve.java, src/main/java/bio/terra/cli/context/CloudResource.java, src/main/java/bio/terra/cli/context/TerraUser.java, src/main/java/bio/terra/cli/context/WorkspaceContext.java, src/main/java/bio/terra/cli/service/WorkspaceManager.java, src/main/java/bio/terra/cli/service/utils/GoogleCloudStorage.java, src/main/java/bio/terra/cli/service/utils/SamService.java
- Added `terra data-refs` commands: `list`, `add`, `delete`, `check-access`, `resolve`.
- Included the user's proxy group email in the TerraUser object and the output of the `terra auth status` command. This is so that it's easier to look up the email that you need to share a bucket with.
```
terra auth status
Current Terra user: mmdevverily@gmail.com
Current Terra user's proxy group: PROXY_110017243614237806241@dev.test.firecloud.org
LOGGED IN
```
- The `check-access` command (currently only for buckets) checks for `objects.list` permission. I'm not sure if this is the right thing long-term -- perhaps we need flags for different access checks (e.g. `terra check-access --writer`)? -- but this is just a guess at what might be useful.
=> PF-483: Add data-refs commands.

src/main/java/bio/terra/cli/command/notebooks/Create.java
Set the terra workspace id as metadata on created Notebooks instance VM metadata.
While this isn't a full solution for auto populating useful Terra variables for a seamless notebooks experience, this does make the workspace id accessible programmatically from the VM, which we can use for further integration.
See https://cloud.google.com/compute/docs/storing-retrieving-metadata
=> PF-527 Add the workspace id to the Notebooks instance metadata.

src/main/java/bio/terra/cli/context/WorkspaceContext.java, src/main/java/bio/terra/cli/service/WorkspaceManager.java
Fixed a bug where the list of cloud resources were not being cleared by `terra workspace delete`.
Note that the CLI is not yet calling WSM to manage controlled resources or data references. This code change is to the temporary code that manages these things locally.
=> PF-563: Clear workspace context file on delete.

.github/workflows/on-pr-merge.yml
- Added a GH action to add a GH tag and bump the version string in `build.gradle` on each merge to the `main` branch.
- The tag bumper action uses the BroadBot GH token, added to this repo by DevOps.
- Left a placeholder step for calling the `publish-release.sh` script in a future PR (needs secrets added to GH repo).
=> PF-569: Bump version on merge to main with GH action.

README.md, build.gradle, src/main/java/bio/terra/cli/apps/DockerAppsRunner.java, src/main/java/bio/terra/cli/command/Workspace.java, src/main/java/bio/terra/cli/command/workspace/List.java, src/main/java/bio/terra/cli/service/WorkspaceManager.java, src/main/java/bio/terra/cli/service/utils/WorkspaceManagerService.java
- Added a `terra workspace list` command to list all workspaces the user has read access to.
* If there is a workspace already mounted, it starts this one.
* Optional `--offset` flag for users with many workspaces. Default is to start from the beginning. Each call fetches up to 30 workspaces.
- Updated the README to include the new command, and notes from yesterday's NF demo.
- Cleaned up some incorrect `@throws` Javadocs after the recent exception handling refactoring.
=> PF-533: List workspaces command

src/main/java/bio/terra/cli/apps/DockerAppsRunner.java, src/main/java/bio/terra/cli/command/config/GetValue.java, src/main/java/bio/terra/cli/command/config/List.java, src/main/java/bio/terra/cli/command/config/Set.java, src/main/java/bio/terra/cli/command/config/getvalue/Logging.java, src/main/java/bio/terra/cli/command/config/set/Logging.java, src/main/java/bio/terra/cli/context/GlobalContext.java, src/main/java/bio/terra/cli/context/utils/Logger.java
- Added two new config commands: `terra config set logging`, `terra config get-value logging`.
- The `set` command allows updating the logging level in the global context without re-compiling.
- Also fixed a small un-related bug. The `terra config set image` command was not updating the image path in the global context if the image had not yet been downloaded with `docker pull`. Changed the behavior to always update the global context property, but log a warning if the image is not found.
=> PF-542: Config command for logging level

src/main/resources/servers/all-servers.json, src/main/resources/servers/terra-verily-dev.json, src/main/resources/servers/terra-verily.json
Added a new server specification that points to the Verily deployment of dev WSM + Broad dev SAM.
CLI users can switch the server they're talking to with:
```
> terra server set terra-verily-dev
Terra server: terra-verily-dev (CHANGED FROM terra-dev)
> terra server status
Current server: terra-verily-dev (Terra development environment deployed at Verily.)
Server status: OKAY
```
=> PF-609: Add CLI server definition for Verily deployment.

src/main/java/bio/terra/cli/command/spend/Disable.java, src/main/java/bio/terra/cli/command/spend/Enable.java, src/main/java/bio/terra/cli/command/spend/ListUsers.java, src/main/java/bio/terra/cli/command/workspace/AddUser.java, src/main/java/bio/terra/cli/command/workspace/Create.java, src/main/java/bio/terra/cli/command/workspace/Delete.java, src/main/java/bio/terra/cli/command/workspace/List.java, src/main/java/bio/terra/cli/command/workspace/ListUsers.java, src/main/java/bio/terra/cli/command/workspace/Mount.java, src/main/java/bio/terra/cli/command/workspace/RemoveUser.java
This is part 4 of the changes to have:
- all commands extend a common base class
- optionally include a --format=json flag
The initial changes, including the definition of the common base class and optional format flag are in PR #40.
This PR includes changes to the `spend` and `workspace` commands.
=> PF-446: Common base class for commands. (part 4)

src/main/java/bio/terra/cli/command/Status.java, src/main/java/bio/terra/cli/command/helperclasses/FormatOption.java, src/main/java/bio/terra/cli/command/notebooks/Create.java, src/main/java/bio/terra/cli/command/notebooks/Delete.java, src/main/java/bio/terra/cli/command/notebooks/Describe.java, src/main/java/bio/terra/cli/command/notebooks/List.java, src/main/java/bio/terra/cli/command/notebooks/Start.java, src/main/java/bio/terra/cli/command/notebooks/Stop.java, src/main/java/bio/terra/cli/command/resources/Create.java, src/main/java/bio/terra/cli/command/resources/Delete.java, src/main/java/bio/terra/cli/command/resources/Describe.java, src/main/java/bio/terra/cli/command/resources/List.java, src/main/java/bio/terra/cli/command/server/List.java, src/main/java/bio/terra/cli/command/server/Set.java, src/main/java/bio/terra/cli/command/server/Status.java
This is part 3 of the changes to have:
- all commands extend a common base class
- optionally include a --format=json flag
The initial changes, including the definition of the common base class and optional format flag are in PR #40.
This PR includes changes to the `notebooks`, `resources` and `server` commands. Also:
- I made the `--format` option visible to command help.
- I removed the output for the `server set` command. To see the current/updated values, users can call the `terra status` command, instead. I think this makes it a little more consistent (i.e. always call `terra status` instead of relying sometimes on the output of `server set`).
=> PF-446: Common base class for commands. (part 3)

src/main/java/bio/terra/cli/command/config/List.java, src/main/java/bio/terra/cli/command/config/getvalue/Browser.java, src/main/java/bio/terra/cli/command/config/getvalue/Image.java, src/main/java/bio/terra/cli/command/config/getvalue/Logging.java, src/main/java/bio/terra/cli/command/config/set/Browser.java, src/main/java/bio/terra/cli/command/config/set/Image.java, src/main/java/bio/terra/cli/command/config/set/Logging.java, src/main/java/bio/terra/cli/command/datarefs/CheckAccess.java, src/main/java/bio/terra/cli/command/groups/AddUser.java, src/main/java/bio/terra/cli/command/groups/Create.java, src/main/java/bio/terra/cli/command/groups/Delete.java, src/main/java/bio/terra/cli/command/groups/Describe.java, src/main/java/bio/terra/cli/command/groups/List.java, src/main/java/bio/terra/cli/command/groups/ListUsers.java, src/main/java/bio/terra/cli/command/groups/RemoveUser.java
This is part 2 of the changes to have:
- all commands extend a common base class
- optionally include a `--format=json` flag.
The initial changes, including the definition of the common base class and optional format flag are in PR #40.
This PR includes changes to the `config` and `groups` commands. Also:
- Removed the output for the `config set` commands. To see the current/updated values, users can call the `config get-value` commands, instead. I think this makes it a little more consistent (i.e. always call `get-value` instead of relying sometimes on the output of `set`).
=> PF-446: Common base class for commands. (part 2)

src/main/java/bio/terra/cli/command/Main.java, src/main/java/bio/terra/cli/command/helperclasses/BaseCommand.java
This is **part 5** of the changes to have:
- all commands extend a common base class
- optionally include a --format=json flag
The initial changes, including the definition of the common base class and optional format flag are in PR #40.
This PR is the **final** change. It moves logging setup from the `Main` picocli entrypoint class into the `BaseCommand` class. Logging levels are stored in the global context, so we need to setup logging after reading in the global context file. This change moves the logging setup into `BaseCommand` so that we're not reading in the global context file twice for each command.
**NOTE** All the previous PRs (parts 2,3, and 4) can be merged in any order. This PR (part 5) must be merged last. Otherwise, commands that are not yet migrated to use the common base …
=> PF-446: Common base class for commands. (part 5)

build.gradle, src/main/java/bio/terra/cli/command/Status.java, src/main/java/bio/terra/cli/command/Workspace.java, src/main/java/bio/terra/cli/command/workspace/Create.java, src/main/java/bio/terra/cli/command/workspace/List.java, src/main/java/bio/terra/cli/command/workspace/Update.java, src/main/java/bio/terra/cli/context/WorkspaceContext.java, src/main/java/bio/terra/cli/service/WorkspaceManager.java, src/main/java/bio/terra/cli/service/utils/WorkspaceManagerService.java
- Bump the WSM client library to the latest version.
- Include the workspace display name and description in the output of `terra status` and `terra workspace list`.
- Added optional flags to specify the display name and description in `terra workspace create`.
- Added a new `terra workspace update` command to allow modifying these mutable properties.
TODO: The `terra workspace update` command always prints out these `WARNING` messages. I'm not sure the cause -- but it seems to be triggered by the client library call `workspaceApi.updateWorkspace` in `WorkspaceManagerService`.
```
> terra workspace create --name="ws_name" --description="ws_description"
Workspace successfully created: dbed98b9-180f-4ee3-b141-8858f6472942
> terra status
Terra server: terra-dev
Terra workspace id: …
```
=> PF-534: Workspace name and description.

docker/Dockerfile, tools/build-docker.sh, tools/download-install.sh, tools/install.sh, tools/local-dev.sh, tools/publish-docker.sh, tools/publish-release.sh
Google doesn't support versions indefinitely on apt-get install. Bump to the latest gcloud sdk version as a fix to stop docker image builds from failing.
Filed PF-665 for consideration of a longer term fix that won't break in ~2 months after there have been 10 more weekly releases from Google.
https://github.com/DataBiosphere/terra-cli/runs/2238110791
```
E: Version '326.0.0-0' for 'google-cloud-sdk' was not found
The command '/bin/sh -c echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list     && apt-get install apt-transport-https ca-certificates gnupg -y     && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg …
```
=> PF-665 bump gcloud sdk version to temporarily unbreak Dockerfile.

src/main/java/bio/terra/cli/command/datarefs/Add.java, src/main/java/bio/terra/cli/context/CloudResource.java, src/main/java/bio/terra/cli/service/WorkspaceManager.java, src/main/java/bio/terra/cli/service/utils/GoogleBigQuery.java
This add support for using BigQuery datasets in both the `resources` and `data-refs` commands.
This is our second resource type. I'm not really sold on our interfaces with the `WorkspaceManager` class and the switch statements everywhere. On the other hand, this is likely to get a major revision once we switch to using WM APIs instead of direct cloud access for create/delete/list, so I'm not sure how much investment to put in at this point.
=> PF-663 Add support for big query datasets as another resource type.

README.md, src/main/java/bio/terra/cli/command/Resources.java, src/main/java/bio/terra/cli/command/resources/Resolve.java
This is a convenience command for getting the cloud id of a controlled resource. It parallels the 'data-refs resolve' command.
=> PF-662 add a 'resources resolve' command.

src/main/resources/servers/all-servers.json, src/main/resources/servers/verily-cli.json
This adds configuration for the newly created `verilycli` personal environment. Unlike other personal environments, this WSM instance points to dev RBS, so projects will not be cleaned up by Janitor. This is intended to be similar to dev, but will be manually synced instead of automatically updated every time WSM head is changed. This should give us more stability for development without blocking backwards-incompatible WSM changes.
In the near-future, this will be set as the default WSM server. I'm not doing that yet so we have some time to transition existing workspaces.
From CONTRIBUTING.md it seems like I don't need to do any manual publishing, it should all be handled by GHA. Is that true?
=> [PF-634] Add verily-cli environment

src/main/java/bio/terra/cli/service/WorkspaceManager.java
As-is, you can create resources using whatever project your gcloud is currently configured to, but the local record doesn't get persisted anywhere. This is surprising, and we should instead just require a workspace context.
When we have WM managed resources and data-refs, it should be possible to do operations without a context but with a specified workspace id.
Passing around potentially "null" workspaceContexts seems error prone to me, but not trying to do a larger change before talking to Mariko.
=> PF-663 require the workspace context for resource and dataref operations

src/main/java/bio/terra/cli/apps/DockerAppsRunner.java, src/main/java/bio/terra/cli/auth/GoogleCredentialUtils.java, src/main/java/bio/terra/cli/command/Main.java, src/main/java/bio/terra/cli/command/groups/ListUsers.java, src/main/java/bio/terra/cli/command/helperclasses/BaseCommand.java, src/main/java/bio/terra/cli/command/helperclasses/FormatOption.java, src/main/java/bio/terra/cli/command/workspace/List.java, src/main/java/bio/terra/cli/context/utils/Printer.java
- Added a singleton `Printer` utility class that holds pointers to the output streams we can write to.
- This removes the various places that hard-coded `System.out` and `System.err`, so that this is only specified in a single central place. The goal is to make this easy to change (in code or by users via global context) in the future.
- Also changed the Docker command output to write to stderr instead of stdout. This should make it easier for the commands that invoke Docker to also specify a return value by writing to stdout.
(This is a follow-on ticket from the JSON format flag/base command general overhaul/cleanup.)
- Note that one [approach for picocli testing](https://picocli.info/#_black_box_and_white_box_testing) is to specify output streams other than `System.out` and `System.err` …
=> PF-603: Hold pointers to output streams in a central place.

src/main/java/bio/terra/cli/command/Server.java, src/main/java/bio/terra/cli/command/config/GetValue.java, src/main/java/bio/terra/cli/command/config/List.java, src/main/java/bio/terra/cli/command/config/Set.java, src/main/java/bio/terra/cli/command/config/getvalue/Server.java, src/main/java/bio/terra/cli/command/config/set/Server.java, src/main/java/bio/terra/cli/command/server/Set.java, tools/install.sh, tools/local-dev.sh
- Included the server setting into the `terra config` group of commands.
- `terra config server set` duplicates the existing `terra server set`. So the server setting can now be changed in the general `config` group of commands, or in the `server` group of commands.
- `terra config get-value server` is a new command to fetch the current server name.
- `terra config list` includes the current server name.
- Updated the server specification in the install and local-dev scripts.
- The scripts now look up the current server, and call `terra config server set` with that value.
- This will not change the server, but will pick up any changes to the server specification files in the code (i.e. in the `resources/server/*.json` files).
=> PF-598: Update server specification on install

docker/Dockerfile
Install the gcloud SDK in the Docker image by downloading a versioned archive, instead of using `apt-get`. Gcloud SDK [documentation](https://cloud.google.com/sdk/docs/install) says that the last 10 releases will be available via `apt-get`. This change allows us to pin the version indefinitely, instead of getting errors every ~10 weeks when the version we pinned is no longer available via `apt-get`. We should still try to keep this up to date, but don't want to cause breakages in case we forget.
I considered always using the latest version of gcloud sdk, but decided against it because that's inconsistent with how we handle most other dependencies (e.g. in `build.gradle` and `nextflow` in the Docker image). As Will pointed out, it's also clunkier to track which CLI release uses which …
=> PF-665: Install gcloud SDK from versioned archive.

src/main/java/bio/terra/cli/service/utils/SamService.java, src/main/java/bio/terra/cli/service/utils/SpendProfileManagerService.java
If `terra spend enable` fails with a user not found in SAM error, then try to invite the user before enabling spend.
This is similar behavior to when:
- `terra workspace add-user` fails with a user not found in SAM error. In this case, we also try to invite the user before adding them to the workspace.
- `terra auth login` or any command requiring an active login fails with a user not found in SAM error. In this case, we try to register the user before executing the command.
=> PF-620: Invite user if `terra spend enable` fails with user not found in SAM.

docker/scripts/terra_init.sh, src/main/java/bio/terra/cli/command/notebooks/Create.java
Allow the solutions team to iterate on a post-startup-script in the short term. Long term, this will be a parameter on the WM create notebook instance api.
=> PF-713 Add a --post-startup-script option for notebooks create.

CONTRIBUTING.md, README.md, src/main/java/bio/terra/cli/command/Main.java, src/main/java/bio/terra/cli/command/app/passthrough/Bq.java, src/main/java/bio/terra/cli/command/app/passthrough/Gcloud.java, src/main/java/bio/terra/cli/command/app/passthrough/Gsutil.java, src/main/java/bio/terra/cli/command/app/passthrough/Nextflow.java
- Updated the README to include descriptions of the exit codes. This is a follow-on task from https://github.com/DataBiosphere/terra-cli/pull/56, specifically a request from John.
- Changed the main usage to include the pass-through app commands (i.e. `gsutil`, `gcloud`, `bq`, `nextflow`). Previously these were hidden and you could only list them with `terra app list`. Un-hiding them per a request from Nicole.
- Also fixed a few other out-of-date sections of the README and CONTRIBUTING docs.
=> PF-704: Update README with exit codes, un-hide pass-through app commands.

src/main/java/bio/terra/cli/service/utils/HttpUtils.java, src/main/java/bio/terra/cli/service/utils/SamService.java, src/main/java/bio/terra/cli/service/utils/WorkspaceManagerService.java
- Added a new utility method `HttpUtils#callAndHandleOneTimeError` for the pattern: try something/handle a one-time error/try again.
- Updated the three places in the CLI that follow this pattern to use the new utility method:
- Add a user to a workspace (try to add, invite the user if they're not found, try adding again)
- Enable a user on spend profile (try to enable, invite the user if they're not found, try enabling again)
- Fetch user info (try to fetch, register the user if they're not found, try fetching again)
This is a follow-on ticket from [PF-620](https://github.com/DataBiosphere/terra-cli/pull/59), specifically from one of Will's comments. This code may not be merged -- it is a tech debt/code cleanup ticket with no effect on the behavior of the CLI, so it should only go in if …
=> PF-714: Handle one-time error pattern.

build.gradle, src/main/java/bio/terra/cli/service/utils/WorkspaceManagerService.java
- Replaced a "not implemented yet" exception with a call to the WSM endpoint to delete a controlled BQ dataset resource.
- Bumped the WSM client library version to include the new endpoint.
=> PF-707: Call WSM endpoint to delete controlled BQ datasets.

README.md, build.gradle, src/main/java/bio/terra/cli/command/helperclasses/options/Format.java, src/main/java/bio/terra/cli/command/resources/create/GcsBucket.java, src/main/java/bio/terra/cli/context/GlobalContext.java, src/main/java/bio/terra/cli/context/ServerSpecification.java, src/main/java/bio/terra/cli/context/WorkspaceContext.java, src/main/java/bio/terra/cli/context/resources/GcsBucketLifecycle.java, src/main/java/bio/terra/cli/context/resources/GcsStorageClass.java, src/main/java/bio/terra/cli/context/utils/FileUtils.java, src/main/java/bio/terra/cli/context/utils/JacksonMapper.java, src/main/java/bio/terra/cli/service/ServerManager.java, src/main/java/bio/terra/cli/service/WorkspaceManager.java, src/main/java/bio/terra/cli/service/utils/WorkspaceManagerService.java
- Added two new options to the `terra resources create gcs-bucket` command, to allow specifying bucket lifecycle rules.
- `--lifecycle` takes a path to a JSON-formatted file that specifies the lifecycle rules. The expected format for this file matches that used by the `gsutil lifecycle` [command](https://cloud.google.com/storage/docs/gsutil/commands/lifecycle). This structure is a subset of the GCS resource [specification](https://cloud.google.com/storage/docs/json_api/v1/buckets#lifecycle).
- `--auto-delete` takes a number of days. This option is a shortcut for specifying a lifecycle rule that auto-deletes objects in the bucket after some number of days.
- Included example JSON files for specifying lifecycle rules in the README.
- Defined CLI-specific classes for specifying the lifecycle …
=> PF-486: Expose bucket lifecycle rules.

src/main/java/bio/terra/cli/context/WorkspaceContext.java, src/main/java/bio/terra/cli/service/WorkspaceManager.java, src/main/java/bio/terra/cli/service/utils/HttpUtils.java, src/main/java/bio/terra/cli/service/utils/WorkspaceManagerService.java
- Added `pollWithRetries` utility method that polls or retries a specified number of times, with a sleep in between each.
- Poll = check the result of an operation to see if it's done (e.g. polling to see if a job is done)
- Retry = try an operation again if a specific kind of exception is thrown (e.g. retry after 500 errors)
- This is basically the same as the existing `callWithRetries` utility method, except that it takes an additional lambda parameter `isDone` and tests the result each time instead of just returning the first result that doesn't throw an exception.
- Called the new method when:
- Deleting a controlled GCS bucket resource
- Creating a new workspace
- Increased the default number of retries from 10 -> 30.
- Also fixed an unrelated bug, where the resources cache was not …
=> PF-719: Utility method for polling with retries.

src/main/java/bio/terra/cli/service/utils/WorkspaceManagerService.java
Removed the hard-coded storage class and lifecycle rule when creating a controlled GCS bucket. This is no longer needed now that WSM has implemented defaults. Previously, it threw a 500 error if these were not specified.
** Note: I also synced the `verily-cli` personal environment for solutions' team testing with the latest WSM code, so that this fix will work against that deployment also.
=> PF-718: Remove hardcoded storage class and lifecycle rule.

tools/local-dev.sh
Added `set +e` to the `local-dev.sh` script. This script is typically called with `source` and so it modifies the calling shell. So after you run `source tools/local-dev.sh`, the next time you run a failing command (e.g. `git stats` instead of `git status`) the shell process exits.
We could also just remove this option in the script, but I think the option is sometimes helpful, and unsetting it on a successful run seems like a good compromise.
=> [no ticket] Restore bash e option in local-dev script.

CONTRIBUTING.md, src/main/java/bio/terra/cli/context/GlobalContext.java
By default, the global context directory is stored in the user's home directory (`$HOME`). Added an option to override this with the `TERRA_CONTEXT_PARENT_DIR ` environment variable.
This will be useful for testing, so that tests don't overwrite an existing installation on the same machine.
=> PF-784: Add env var override for context directory parent.

CONTRIBUTING.md, build.gradle, src/main/java/bio/terra/cli/auth/AuthenticationManager.java, src/main/java/bio/terra/cli/auth/GoogleCredentialUtils.java, src/main/java/bio/terra/cli/context/GlobalContext.java, src/main/java/bio/terra/cli/context/TerraUser.java, src/test/java/auth/LoginTestUser.java, src/test/java/harness/TestContext.java, src/test/java/harness/TestUsers.java, tools/render-config.sh
- Implemented domain-wide delegation for CLI test uesrs.
- Added the `TestUsers` class that lists the test users available for CLI tests and includes a `login` method. This `login` method mimics the typical CLI login flow in a way that is more useful for testing, because it doesn't require manual interaction with a browser.
- Wrote two unit tests to check that
- The domain-wide delegated credentials were getting populated in the global context correctly
- All the test users are enabled in SAM.
- Updated the `render-config.sh` script to also pull a firecloud SA for domain-wide delegation.
- Added section to CONTRIBUTING.md with instructions for setting up test users on a new Terra environment.
- Made some small changes to the authentication code to support testing.
- Populate the access …
=> PF-787: Domain-wide delegation for CLI test users.

.github/workflows/tests-nightly.yml, .github/workflows/tests-on-pr-push-and-merge.yml, src/test/resources/testscripts/DeleteWorkspace.sh, src/test/resources/testscripts/NextflowRnaseq.sh
- Added a new GitHub action to run tests nightly.
- Runs unit tests in job 1.
- Runs integration tests against an installation built from source code via `./gradlew installDist` in job 2.
- Runs integration tests against an installation built from the latest GitHub release in job 3.
- Each test job uploads a GitHub action archive with the global context file and all log files generated during the test run.
- Two other fixes/changes:
- Fixed a bug in the Nextflow integration test. It was fine on the Linux GH action runner, but on my Mac `uuidgen` produces uppercase letters, which are [not allowed](https://cloud.google.com/storage/docs/naming-buckets#requirements) for GCS bucket names.
- Removed the integration test cleanup code that deleted all resources before deleting a workspace. WSM …
=> PF-757: Run tests nightly.

.github/workflows/tests-nightly.yml, .github/workflows/tests-on-pr-push-and-merge.yml, src/main/java/bio/terra/cli/serialization/userfacing/UFResource.java, src/main/java/bio/terra/cli/serialization/userfacing/resources/UFAiNotebook.java, src/main/java/bio/terra/cli/serialization/userfacing/resources/UFBqDataset.java, src/main/java/bio/terra/cli/serialization/userfacing/resources/UFGcsBucket.java, src/test/java/harness/TestCommand.java, src/test/java/harness/TestGCSBucketReferences.java, src/test/java/harness/TestUsers.java, src/test/java/harness/baseclasses/SingleWorkspaceUnit.java, src/test/java/harness/utils/ExternalGCSBuckets.java, src/test/java/unit/AuthStatus.java, src/test/java/unit/GcsBucketControlled.java, src/test/java/unit/GcsBucketReferenced.java, src/test/java/unit/Workspace.java, src/test/java/unit/WorkspaceUser.java
- Added tests for referenced and controlled GCS bucket resources.
- The referenced GCS bucket tests generate buckets in an external project using a SA. This project is currently set to `terra-cli-dev`, but should be changed in a future ticket to use different hard-coded project + SA that is generated by Terraform (PF-829).
- Removed some Jackson annotations in the `UFResource` classes so that we don't include the `@class` property in the user-facing command output.
=> PF-825: Tests for referenced and controlled GCS bucket resources.

README.md, src/main/java/bio/terra/cli/apps/CommandRunner.java, src/main/java/bio/terra/cli/apps/DockerCommandRunner.java, src/main/java/bio/terra/cli/apps/LocalProcessCommandRunner.java, src/main/java/bio/terra/cli/apps/utils/DockerClientWrapper.java, src/main/java/bio/terra/cli/command/Main.java, src/main/java/bio/terra/cli/exception/PassthroughException.java, src/test/java/unit/PassthroughApps.java
Pass-through apps are third-party tools that users can call in the context of a workspace by prefixing it with `terra`. e.g.
`terra nextflow run ...`, `terra gsutil ls ...`
- Fixes:
- Output from pass-through apps now prints to standard out. Previously it was printing to standard error.
- The process exit code is now passed through to the CLI caller. Previously it was swallowed and the CLI always returned 0 = success.
- Added unit tests.
=> PF-798: Fix and tests for pass through app commands.

tools/install.sh
This is causing some errors in the notebooks post startup script where the CLI install doesn't finish with a successful error code (even though the CLI is actually basically set up by the time it errors here).
This breaks backwards compatibility for installing some past version where the set server didn't use `--name`.
=> [no ticket] fix set server command in install script

src/main/java/bio/terra/cli/service/SamService.java, src/main/java/bio/terra/cli/service/WorkspaceManagerService.java, src/main/java/bio/terra/cli/service/utils/HttpUtils.java
- Add retries for WSM calls and include more retryable status code for SAM calls.
- Both now retry 500, 502, 503, 504 (so all the 5xx except 501 not implemented, 505 http version not supported).
- Also fixed a bug where adding a user to a SAM group failed with a bad request if the user is not already registered. Changed to invite the user if they're not found, and then add them to the group.
=> PF-513: Add retries to WSM calls.

notebooks/post-startup.sh
Change from piping outputs to /tmp/ so that they aren't as easily deleted.
=> [no-ticket] Move post startup script debug output to user directory

build.gradle, src/main/java/bio/terra/cli/businessobject/Server.java, src/main/java/bio/terra/cli/service/WorkspaceManagerService.java, src/test/java/harness/TestCommand.java, src/test/java/unit/Server.java, src/test/resources/testinputs/BadServer.json, tools/local-dev.sh
- Bumped the WSM client library to a version that includes recent changes to the `/status` endpoint.
- Changed the WSM `/status` endpoint call to no longer expect a return object.
- Added tests for the `server` group of commands.
- Fixed a bug in the `local-dev.sh` setup script when setting the current server.
=> PF-856: WSM `/status` changes. Tests for `server` commands.

CONTRIBUTING.md, src/test/java/harness/TestUsers.java, src/test/java/harness/utils/SamGroups.java, src/test/java/unit/Group.java, src/test/java/unit/SpendProfileUser.java, tools/setup-test-users.sh
- Tests for the `group` commands, which manage SAM groups.
- Tests for the `spend` commands, which manage access to the WSM default spend profile.
- For testing the `spend` commands, I didn't want to use any of the test users, because that could cause problems if tests get run simultaneously. Instead, I generate a SAM group, use its accompanying email in the tests, then delete the group. This is just a workaround until we have a way to generate test users and clean them up in SAM afterwards.
=> PF-797: Tests for `group` and `spend` commands.

src/main/java/bio/terra/cli/apps/LocalProcessCommandRunner.java, src/test/java/harness/TestBashScript.java, src/test/java/integration/Nextflow.java, src/test/java/unit/PassthroughApps.java, src/test/resources/testscripts/DeleteWorkspace.sh, src/test/resources/testscripts/NextflowHelloWorld.sh
Pass-through apps are third-party tools that users can call in the context of a workspace by prefixing it with `terra`. e.g.
`terra nextflow run ...`, `terra gsutil ls ...`. They can be run in 2 modes:
- `DOCKER_CONTAINER` is the default and means that the app is run in a docker container shipped with the CLI and pre-installed with supported tools (e.g. `nextflow`, `gcloud`).
- `LOCAL_PROCESS` means that the app is run in a child process on the local machine and uses tools that are installed locally. The CLI doesn't have any control over what's installed locally, but this can be useful to users who want to run apps that are not yet supported by Terra.
-------------------------
- The process exit code is now passed through to the CLI caller for `LOCAL_PROCESS` mode. Previously it was …
=> PF-857: Fix exit code for pass through apps run in local process mode.

src/main/java/bio/terra/cli/apps/LocalProcessCommandRunner.java, src/main/java/bio/terra/cli/command/config/GetValue.java, src/main/java/bio/terra/cli/command/config/List.java, src/main/java/bio/terra/cli/command/config/Set.java, src/main/java/bio/terra/cli/command/config/getvalue/Workspace.java, src/main/java/bio/terra/cli/command/config/set/Workspace.java, src/main/java/bio/terra/cli/serialization/userfacing/UFConfig.java, src/test/java/integration/Config.java, src/test/java/unit/Config.java
- Added workspace as a config property.
- `terra config set workspace` is identical to the existing `terra workspace set`. This is just for convenience, similar to how there are identical `terra config set server` and `terra server set`.
- `terra config get-value workspace` returns the current workspace id.
- The current workspace id is now included in the output of `terra config list`.
- Added tests for the `config` group of commands.
- Fixed a bug where the `gcloud` project config property was not being restored if it was previously unset. This happened when executing apps in the LOCAL_PROCESS mode only.
=> PF-796: Workspace config command. Config tests.

CONTRIBUTING.md, src/main/java/bio/terra/cli/command/Main.java, src/main/java/bio/terra/cli/command/groups/Describe.java, src/main/java/bio/terra/cli/service/SamService.java, src/main/java/bio/terra/cli/service/WorkspaceManagerService.java, src/main/java/bio/terra/cli/service/utils/HttpUtils.java, src/test/java/unit/ClientExceptionHandling.java
- Consolidated handling of exceptions thrown by the client or retires into one place each for SAM and WSM. This removed a lot of boilerplate try/catch/wrap and re-throw logic in the methods of these classes.
- Added logic to try and parse the `ErrorReport` returned by SAM and WSM in the response body when an error occurs.
- Added logging so we always have the status code, response body, and exception message for SAM and WSM client exceptions, even if they're in an unexpected format or property.
- Wrote two unit tests to make sure the SAM and WSM error message gets written out to the user.
- Overloaded some of the `HttpUtils` methods that do retries to also accept lambdas that don't return a value. This removed boilerplate `() -> { something...; return null; }` when we wanted to do retries …
=> PF-860, PF-868: Consolidate handling of SAM, WSM client exceptions.

src/test/java/unit/GcsBucketLifecycle.java
Enable the GCS bucket lifecycle tests for the properties: `customTimeBefore`, `daysSinceCustomTime`, `daysSinceNoncurrentTime`, `noncurrentTimeBefore`.
These properties were not supported by WSM until PF-506 was merged recently.
=> [no ticket]: Enable GCS bucket lifecycle tests that weren't supported before.

.github/workflows/cleanup-test-user-workspaces.yml, .github/workflows/tests-nightly.yml, build.gradle, src/test/java/harness/TestUsers.java, src/test/java/harness/utils/CleanupTestUserWorkspaces.java
- Added a script to cleanup test user owned workspaces.
- Added an on-demand GitHub action to trigger the script. I made this on-demand because it can't be run concurrently with any tests. It will cause tests to fail as workspaces are deleted out from under them. We could run this at night, e.g. just after the nightly tests, but that could cause problems if someone decides to re-run the nightly GH action during the day (e.g. failed overnight, fix went in, and now re-run).
=> PF-821: Script to cleanup test user owned workspaces.

src/main/java/bio/terra/cli/businessobject/Server.java, src/main/java/bio/terra/cli/serialization/persisted/PDServer.java, src/main/java/bio/terra/cli/serialization/userfacing/UFServer.java, src/main/java/bio/terra/cli/service/SpendProfileManagerService.java, src/main/java/bio/terra/cli/service/WorkspaceManagerService.java, src/main/resources/servers/all-servers.json, src/main/resources/servers/mm-dev.json, src/main/resources/servers/terra-dev.json, src/main/resources/servers/terra-verily-autopush.json, src/main/resources/servers/terra-verily-dev.json, src/main/resources/servers/verily-cli.json, src/main/resources/servers/wchamber-dev.json, src/test/resources/testinputs/BadServer.json
- Added a property to the server specification for the WSM default spend profile. Previously, this was hard-coded to "wm-default-spend-profile".
- Added a separate server specification for the Verily autopush environment, and updated the one for the Verily dev environment.
Eventually, there will be a spend profile manager service and users will want to specify a spend profile to use (e.g. on workspace create or as a CLI config property, etc.). When that time comes, this property will need to be removed. But for now, there is only a single hard-coded spend profile for each WSM deployment. This PR brings the CLI in-line with this association; the spend profile is now a property of the server.
=> PF-890: Make WSM default spend profile a property of the server.

src/main/java/bio/terra/cli/businessobject/Resource.java, src/main/java/bio/terra/cli/businessobject/User.java, src/main/java/bio/terra/cli/businessobject/resources/AiNotebook.java, src/main/java/bio/terra/cli/businessobject/resources/BqDataset.java, src/main/java/bio/terra/cli/businessobject/resources/GcsBucket.java, src/main/java/bio/terra/cli/command/notebooks/Start.java, src/main/java/bio/terra/cli/command/notebooks/Stop.java, src/main/java/bio/terra/cli/command/resources/CheckAccess.java, src/main/java/bio/terra/cli/serialization/userfacing/resources/UFAiNotebook.java, src/main/java/bio/terra/cli/service/WorkspaceManagerService.java, src/test/java/harness/TestUsers.java, src/test/java/harness/utils/Auth.java, src/test/java/harness/utils/ExternalBQDatasets.java, src/test/java/harness/utils/ExternalGCSBuckets.java, src/test/java/unit/BqDatasetControlled.java, src/test/java/unit/BqDatasetReferenced.java, src/test/java/unit/GcsBucketControlled.java, src/test/java/unit/GcsBucketLifecycle.java, src/test/java/unit/GcsBucketReferenced.java, src/test/java/unit/WorkspaceOverride.java
- Removed the cloud-platform scope from the CLI login flow. Previously, this was needed to create cloud resources on behalf of the user, while the WSM controlled resource endpoints were under development. Now that the CLI always goes through WSM, we don't want to request this scope any more.
- This additional scope was causing logins with Google/Verily corporate emails (i.e. `@google.com`, `@verily.com`) to fail, because there is a corporate policy against granting the cloud-platform scope. This change fixes this.
- Test users still need the cloud-platform scope when they talk to GCP directly (e.g. to query resource properties that are not stored as WSM metadata). Changed the tests to use the same scopes as CLI users, except when they are talking to the cloud directly. In those cases, …
=> PF-889: Remove cloud platform scope from login flow.

src/main/java/bio/terra/cli/command/resources/create/AiNotebook.java
The Google JupyterLab extensions expect projects editor permissions. We're not granting those to users or SAs within workspace projects. Until there is a fully managed AI Notebook service offered by Google, we probably won't be able to use these extensions. Removing them for now.
See also https://broadworkbench.atlassian.net/browse/PF-839
=> PF-839 remove Google JupyterLab extensions metadata.

README.md, src/main/java/bio/terra/cli/businessobject/Context.java, src/main/java/bio/terra/cli/businessobject/User.java, src/main/java/bio/terra/cli/businessobject/Workspace.java, src/main/java/bio/terra/cli/command/shared/BaseCommand.java, src/main/java/bio/terra/cli/command/workspace/Set.java, src/main/java/bio/terra/cli/serialization/persisted/PDWorkspace.java, src/test/java/unit/WorkspaceSetDeferLogin.java, src/test/java/unit/WorkspaceSetSuppressLogin.java
- The motivation for this change is to set the workspace id on an AI notebook in the startup script.
- We want to configure the CLI with the correct workspace for them ahead of time. We know the workspace id, but we don't have the user's credentials yet.
- Previously, setting the workspace id required logging in first so we can fetch the workspace metadata from WSM using the user's credentials. This change removes that requirement, and allows us to defer fetching the workspace metadata to when the user does login.
- Added a `--defer-login` option to the `terra workspace set` command.
- If the user is not already logged in, then the CLI will not prompt for login, but will save the workspace id and load the metadata the next time the user logs in.
- If the user is already logged in, then …
=> PF-887: Allow setting the workspace id without logging in first.

notebooks/README.md, notebooks/post-startup.sh, src/main/java/bio/terra/cli/serialization/userfacing/UFConfig.java
- Updated the notebook startup script to set the workspace id from the VM metadata, similar to how the server is set.
- Fixed a bug in the text output of the `terra config list` command, where the `app-launch` and `browser` property values were swapped.
=> PF-899: Set workspace id in notebook startup script.

.github/workflows/tests-nightly.yml
This modifies the nightly tests to run against both dev and Verily's autopush environment.
I'm not sure if we want to change the notification policy (e.g. only notify for `dev` or something) - 6 is a lot of daily slack messages, even if they are going to an alert-only channel.
=> [PF-741] Run nightly tests against autopush

.github/workflows/cleanup-test-user-workspaces.yml, .github/workflows/release-on-pr-merge.yml, .github/workflows/tests-nightly.yml, .github/workflows/tests-on-pr-push-and-merge.yml, src/test/java/harness/TestExternalResources.java, tools/render-config.sh
The CLI tests for referenced workspace resources create buckets and BQ datasets in an external (to WSM) project. Previously, the tests were using the `terra-cli-dev` project, which was manually created and is intended for holding the client id and GCR repository only. This PR changes the tests to use the `terra-cli-test` project, which was Terraformed specifically for CLI tests (see related terraform-ap-modules [PR](https://github.com/broadinstitute/terraform-ap-modules/pull/189) and terraform-ap-deployments [PR](https://github.com/broadinstitute/terraform-ap-deployments/pull/353)).
I also added a new GH secret to this repo for the key file of the new SA.
=> PF-829: Use Terraformed project + SA for creating test resources.

CONTRIBUTING.md, src/test/java/unit/AiNotebookControlled.java, src/test/java/unit/WorkspaceOverride.java
Now that permissions for `notebook start/stop` commands are fixed, re-enabled the tests and assertions for these commands.
=> PF-922: Re-enable notebook tests.

.github/workflows/tests-nightly.yml, CONTRIBUTING.md, build.gradle
Changed the nightly test GH action to run the three types of tests (unit, integration against source code, integration against GH release) serially instead of in parallel. This means the tests take longer to run (~1hr instead of ~35 min), but this is only for the nightly run, so it shouldn't matter. Tests run for PRs still run in parallel. Also compiled the result summary into a single Slack message per server.
- Fixed test run logs/context file getting overwritten by runs on a second server.
- Fixed link to test run not showing up in the Slack message.
Example Slack notification:
The failure is artificial just to show what the message looks like. I expect all tests to pass against both environments.
=> PF-920, PF-921: Fixes for nightly GH action.

.github/workflows/cleanup-test-user-workspaces.yml, src/main/java/bio/terra/cli/businessobject/User.java, src/test/java/harness/utils/CleanupTestUserWorkspaces.java
If a workspace has no cloud context, then it means something went wrong during `workspace create`. In that case, the user should just delete the workspace and create a new one. Previously, this could be difficult to do because loading the workspace would fail when the pet SA fetch from SAM tried to use a null project id. This change is to skip the pet SA fetch if the workspace project id is undefined. This way, the workspace load will succeed and the user can successfully delete it, without errors.
This bug was causing leaked workspaces in tests. When a cloud context failed to be created, the test cleanup failed to delete the corrupted workspace.
=> PF-927: Allow deleting a workspace with no cloud context.

.github/workflows/cleanup-test-user-workspaces.yml, .github/workflows/release-on-pr-merge.yml, .github/workflows/tests-nightly.yml, .github/workflows/tests-on-pr-push-and-merge.yml, build.gradle, src/test/java/harness/CRLJanitor.java, src/test/java/harness/TestExternalResources.java, src/test/java/harness/baseclasses/SingleWorkspaceUnit.java, src/test/java/harness/utils/ExternalBQDatasets.java, src/test/java/harness/utils/ExternalGCSBuckets.java, src/test/java/unit/AiNotebookControlled.java, src/test/java/unit/BqDatasetReferenced.java, src/test/java/unit/ClientExceptionHandling.java, src/test/java/unit/DeletePrompt.java, src/test/java/unit/GcsBucketLifecycle.java, src/test/java/unit/GcsBucketReferenced.java, src/test/java/unit/WorkspaceOverride.java, src/test/java/unit/WorkspaceSetDeferLogin.java, tools/render-config.sh
- The CLI creates buckets and datasets in an external (to WSM) project for testing referenced resources. This PR changes the setup/cleanup of these buckets and datasets to use CRL with Janitor (in cleanup mode) to make sure they get cleaned up eventually.
- Reading information from the cloud about these buckets and datasets as a user would do continues to use the regular GCS/BQ client library, not the CRL wrapper, because we don't expect CLI users to use CRL.
- Many of the changes in this PR are due to moving from the BQ cloud client library to the api client library, which is what CRL wraps.
- While not part of this PR per se, I also added a new GH secret to this repository for the Janitor client SA key in order to get this working.
=> PF-901: Use CRL Janitor for external buckets, datasets.

notebooks/post-startup.sh
This is a request from the solutions team, so that they can run Nextflow locally on the notebook VM instead of being forced to use the CLI's Docker container via `terra nextflow ...`. When using the CLI's Docker container, you can't use Nextflow's container mode, because that would mean running Docker in Docker, which doesn't work.
The CLI has a config property `app-launch` that controls whether apps, such as Nextflow, are launched in the Docker container or in a local process. One reason this config property was added was to workaround this Docker in Docker problem with Nextflow. The solutions team is going to experiment with using this config property to call the local installation of Nextflow via `terra nextflow ...`, but have asked me to not set it in the startup script just yet.
I've …
=> PF-926: Install Nextflow in the notebook startup script.

src/main/java/bio/terra/cli/command/resource/List.java, src/main/java/bio/terra/cli/serialization/userfacing/UFResource.java, src/test/java/unit/AiNotebookControlled.java, src/test/java/unit/BqDatasetControlled.java, src/test/java/unit/GcsBucketControlled.java
- Included the assigned user for private resources in the text output of `terra resource list`. It was already included in the JSON output.
- Added some null checks around the resource name and description, so we print out empty string instead of "null".
- Removed the TODOs for PF-616 to check the IAM roles for private resources. The team's decision was not to expose these in WSM's API, so there's nothing for the CLI tests to check.
=> PF-915: Include private user in resource list.

README.md, build.gradle, src/main/java/bio/terra/cli/service/GoogleAiNotebooks.java, src/test/java/unit/AiNotebookControlled.java, src/test/java/unit/GcsBucketLifecycle.java
- Notebook start/stop sometimes fails with a 409: unable to queue operation error. Polling the notebook state to make sure that it is ACTIVE/STOPPED before calling stop/start does not prevent this. There is an [open bug](https://github.com/googleapis/java-notebooks/issues/201) against the GCP notebooks Java client for this. In the meantime, I've added a "wait a few minutes and try again" note to the exception message when this error occurs.
- Updated the README with correct commands for giving a user spend profile access.
Test fixes:
- Changed the delete test for a notebook resource to tolerate timeouts in the CLI waiting for the delete job in WSM to complete. In the future this should use long-running job commands, once they are implemented. Reenabled this test.
- Changed the start/stop …
=> PF-928: Make notebook tests more tolerant of timeouts and 409s.

src/main/java/bio/terra/cli/businessobject/WorkspaceUser.java, src/main/java/bio/terra/cli/command/resource/List.java, src/main/java/bio/terra/cli/command/workspace/AddUser.java, src/main/java/bio/terra/cli/command/workspace/RemoveUser.java, src/main/java/bio/terra/cli/serialization/userfacing/UFWorkspaceUser.java, src/test/java/harness/utils/CleanupTestUserWorkspaces.java, src/test/java/unit/BqDatasetControlled.java, src/test/java/unit/GcsBucketControlled.java, src/test/java/unit/WorkspaceOverride.java, src/test/java/unit/WorkspaceUser.java
Defined a CLI enum for workspace user roles: READER, WRITER, OWNER. It is different from the WSM enum for workspace user roles, which also includes the APPLICATION role.
We don't want to expose the APPLICATION role to CLI users at this time. There are no immediate use cases for it, and possible future use cases (e.g. Leo) may not use the CLI to setup the application user anyway. So for now, I've hidden this role from CLI users to avoid confusion. Previously trying to define an application user resulted in an error.
Also fixed an NPE when listing referenced resources in text format.
=> PF-994: Define CLI enum for workspace user roles.

CONTRIBUTING.md, tools/setup-test-users.sh
Added a new argument to the script to setup CLI test users on SAM. The goal is to make sure that the team doesn't lose access if the person who ran the script originally is unavailable. This admin group has to be setup manually.
Outside of this PR, I've setup the `developer-admins` group on the dev SAM deployed at the Broad. This group is an ADMIN on the `cli-test-users` group and the default WSM spend profile resource. This group contains all the corporate emails of the PF team as of today.
=> PF-1005: Take admin group email in test users setup script.

src/main/java/bio/terra/cli/businessobject/User.java, src/main/java/bio/terra/cli/businessobject/Workspace.java, src/main/java/bio/terra/cli/serialization/persisted/PDUser.java, src/main/java/bio/terra/cli/service/SamService.java, src/test/java/unit/PassthroughApps.java
- Fetch a pet SA access token directly from SAM instead of creating one from the cached pet SA key file.
- Fetch the pet SA email directly from SAM instead of reading the client email from the pet SA key.
- With this change, the CLI still fetches the pet SA key file from SAM and caches it locally. Instead of using this key file every time pet SA credentials are needed, now the CLI only uses this file for setting application default credentials on the Docker container for running third-party tools.
This is a first step towards removing use of the pet SA key file from the CLI. Remaining work is to figure out how to not require this for running apps on the Docker container. Once we have a solution for that, then we can remove this pet SA key file fetch and caching from the CLI entirely.
=> PF-1010: Get pet SA token directly from SAM.

CONTRIBUTING.md, src/main/java/bio/terra/cli/businessobject/User.java, src/main/java/bio/terra/cli/businessobject/Workspace.java, src/main/java/bio/terra/cli/command/Workspace.java, src/main/java/bio/terra/cli/command/workspace/BreakGlass.java, src/main/java/bio/terra/cli/service/SamService.java, src/main/java/bio/terra/cli/service/utils/CrlUtils.java, tools/break-glass-bq/tableSchema_requests.json, tools/create-break-glass-bq.sh, tools/render-config.sh, tools/setup-test-users.sh
- Add a hidden command `terra workspace break-glass` to grant Editor access to a workspace project.
- Included a script to create a central BQ dataset for cataloging break-glass requests. The command writes to this dataset.
- More details and example commands in `CONTRIBUTING.md`.
=> PF-1006: Break-glass command.

.github/workflows/tests-nightly.yml, ADMIN.md, CONTRIBUTING.md, README.md, build.gradle, src/main/java/bio/terra/cli/command/Spend.java, src/main/java/bio/terra/cli/command/spend/CreateProfile.java, src/main/java/bio/terra/cli/command/spend/DeleteProfile.java, src/main/java/bio/terra/cli/service/SamService.java, src/main/java/bio/terra/cli/service/SpendProfileManagerService.java, src/main/java/bio/terra/cli/service/WorkspaceManagerService.java, tools/setup-test-users.sh
- Added two new admin commands for setting up/deleting the default spend profile: `terra spend create-profile`, `terra spend delete-profile`
- Changed the nightly tests GH action to run against the `terra-verily-devel` server instead of `terra-verily-autopush`. I've got a successful run [here](https://github.com/DataBiosphere/terra-cli/actions/runs/1304423547).
- Also some smaller changes:
- Improved exception logging when using retries. Previously, we were only logging the last exception message, now all are logged.
- Separated out documentation for the spend profile and break-glass commands into a new ADMIN.md.
- Changed the script for setting up CLI test users to not quit if the SAM group already exists.
Not part of this PR, but as part of this ticket, I've setup the spend profile and …
=> PF-1017: Run nightly tests against devel instead of autopush.

src/main/java/bio/terra/cli/businessobject/User.java, src/main/java/bio/terra/cli/service/GoogleNotebooks.java, src/main/java/bio/terra/cli/service/SamService.java, src/main/java/bio/terra/cli/service/WorkspaceManagerService.java, src/test/java/unit/Workspace.java
Added a better error message when a command fails because a user does not have access to the spend profile. This is now a `UserActionableException` because there is a way for the user to address it: ask an admin to grant them access. This better message should apply regardless of what command the user runs to hit this error (e.g. `workspace create`, `resource create`, etc.).
Previous:
New:
=> PF-1102: Better error message when spend profile access denied.

src/main/java/bio/terra/cli/businessobject/resource/BqDataset.java, src/main/java/bio/terra/cli/businessobject/resource/GcsBucket.java, src/main/java/bio/terra/cli/serialization/userfacing/resource/UFBqDataset.java, src/main/java/bio/terra/cli/serialization/userfacing/resource/UFGcpNotebook.java, src/main/java/bio/terra/cli/serialization/userfacing/resource/UFGcsBucket.java, src/main/java/bio/terra/cli/service/utils/CrlUtils.java
Included the location in the user-facing output (text and JSON) for both bucket and dataset resources. This applies to both controlled and referenced resources. Location is already included for notebooks, so this brings the other resource types in line with that.
=> PF-1087: Include location in bucket and dataset output.

.github/workflows/cleanup-test-user-workspaces.yml, .github/workflows/tests-nightly.yml, .github/workflows/tests-on-pr-push-and-merge.yml, ADMIN.md, CONTRIBUTING.md, README.md, build.gradle, src/main/java/bio/terra/cli/businessobject/Server.java, src/main/resources/servers/all-servers.json, src/main/resources/servers/broad-dev-cli-testing.json, src/main/resources/servers/broad-dev-jcarlton.json, src/main/resources/servers/broad-dev-local-sam.json, src/main/resources/servers/broad-dev-local-wsm.json, src/main/resources/servers/broad-dev-mmedlock.json, src/main/resources/servers/broad-dev-wchamber.json, src/main/resources/servers/broad-dev-zloery.json, src/main/resources/servers/broad-dev.json, src/main/resources/servers/verily-autopush.json, src/main/resources/servers/verily-devel.json, src/main/resources/servers/verily-preprod.json, src/main/resources/servers/verily-staging.json, src/main/resources/servers/verily.json, src/test/java/unit/Config.java, src/test/java/unit/Server.java
Changed all server names to include a prefix (`broad` or `verily`) to indicate where the deployment lives.
The server list has grown over time and there was no consistent naming strategy. This may be causing some confusion lately about which environment we're talking about (especially between the Broad and Verily development environments).
=> PF-1129: Update server names with broad/verily prefix.

src/main/java/bio/terra/cli/command/Main.java, src/test/java/unit/Syntax.java, src/test/java/unit/Workspace.java
Allow any case enum options, e.g. `terra workspace list --format=JSon`
=> [PF-1075] use case-insensitive enum flag

src/main/java/bio/terra/cli/businessobject/Workspace.java, src/main/java/bio/terra/cli/command/workspace/Clone.java, src/main/java/bio/terra/cli/service/WorkspaceManagerService.java
Per discussion in stand-up on 11/22/21, removed the location parameter from the workspace clone command in the CLI because it's not fully implemented in WSM. The intent of this parameter was to provide an override location for the cloned resources. However, each resource type has a different set of possible location values. There is no single concept of location in GCP. We expect that we'll want a concept of workspace location, both for cloning and for a default location. We will hold off exposing this parameter in the CLI workspace clone command until we have this concept implemented in WSM.
Note that the location parameter still makes sense for cloning individual resources, but the CLI does not expose those WSM endpoints -- only the full workspace clone.
=> PF-1219: Remove location parameter from workspace clone command.

src/main/java/bio/terra/cli/service/WorkspaceManagerService.java, src/test/java/unit/Workspace.java
Previously, when context creation failed, we simply aborted the operation, leaving a new stub workspace in the database. With this change, we'll delete such workspaces in this scenario.
=> [PF-1103] delete empty workspace when creating cloud context fails

CONTRIBUTING.md, README.md, src/main/java/bio/terra/cli/command/app/passthrough/Nextflow.java
Added instruction for sending workflow run metrics to a Nextflow Tower instance.
Pulled the Nextflow Tower related environment variables into the Docker container if they are defined on the host machine.
Unrelatedly, also added a section to `CONTRIBUTING.md` about automated tests.
=> PF-1237: Pull NF Tower env vars from host if defined.

src/main/java/bio/terra/cli/command/Main.java, src/main/java/bio/terra/cli/command/shared/BaseCommand.java
```
09:40:41.247 [main] DEBUG bio.terra.cli.command.shared.BaseCommand - [COMMAND RUN] terra config get server
09:40:42.101 [main] DEBUG bio.terra.cli.command.shared.BaseCommand - [COMMAND RUN] terra config set server --name=broad-dev
09:40:42.105 [main] DEBUG bio.terra.cli.utils.JacksonMapper - Serializing object with Jackson to file: /Users/yuhuyoyo/.terra/context.json
09:40:57.988 [main] DEBUG bio.terra.cli.command.shared.BaseCommand - [COMMAND RUN] terra version
09:41:02.261 [main] DEBUG bio.terra.cli.command.shared.BaseCommand - [COMMAND RUN] terra server list
09:41:12.162 [main] DEBUG bio.terra.cli.command.shared.BaseCommand - [COMMAND RUN] terra auth login
09:41:16.186 [main] DEBUG bio.terra.cli.service.utils.HttpUtils - Request attempt #1
09:41:16.596 [main] DEBUG …
```
=> PF-1170: log all the CLI commands in DEBUG level.

src/main/java/bio/terra/cli/businessobject/User.java, src/main/java/bio/terra/cli/service/GoogleOauth.java
Replace the default landing page shown in the browser upon completing the OAuth login flow.
Now it loads the CLI README page instead. Note that this behavior change only applies when the `browser` config property is set to `AUTO` (which launches a browser window on the current computer), not `MANUAL` (which prints a URL for the user to open in a browser themselves).
=> PF-1233: Point to CLI README upon login completion.

src/main/java/bio/terra/cli/businessobject/User.java, src/main/java/bio/terra/cli/command/auth/Revoke.java, src/main/java/bio/terra/cli/command/auth/Status.java
Several small text output string changes for the `auth status` and `auth revoke` commands. One bug fix for the pet SA email not getting cleared in the locally stored context when deleting the current workspace.
- PF-1092: In `terra auth status` text output, change "No current Terra user defined" -> "NO USER LOGGED IN", to make it similar to the text when a user is logged in.
- PF-1094: In `terra auth status` text output, change "Current user" -> "User email" and "Proxy group for current user" -> "Proxy group email", to make it similar to the property names in the JSON output.
- PF-1095: In `terra auth status` text output, change "null" -> "(undefined)" for the pet SA email. Also fix a bug where the pet SA email isn't cleared when the current workspace is deleted.
- PF-1098: In `terra auth …
=> PF-1092, PF-1094, PF-1095, PF-1098: Minor text output string changes for auth commands.

src/main/java/bio/terra/cli/businessobject/Context.java, src/test/java/unit/WorkspaceOverride.java
This change makes the CLI ignore the `--workspace` flag when it's provided and matches the current workspace context. This ensures that local context is still updated if the user calls `terra workspace delete/update --workspace={current workspace ID}` so that the local context is no longer out of date.
I've verified this also fixes the issues in PF-1164 and. PF-1168, though those tickets are already closed.
=> [PF-1160] Ignore workspace flag when it matches current workspace

src/main/resources/servers/verily-preprod.json, src/main/resources/servers/verily.json
This updates the Verily preprod + prod servers to use the correct billing account now that GCP permissions are sorted out. I've also created the appropriate spend profile in each environment and granted permissions to the same users as the current `wm-temp-spend-profile`.
=> [PF-1088] Point verily preprod/prod at new billing account

build.gradle, src/main/java/bio/terra/cli/command/resource/update/BqDataset.java, src/main/java/bio/terra/cli/command/resource/update/BqTable.java, src/main/java/bio/terra/cli/command/resource/update/GcsObject.java, src/main/java/bio/terra/cli/serialization/userfacing/input/UpdateReferencedBqDatasetParams.java, src/main/java/bio/terra/cli/serialization/userfacing/input/UpdateReferencedBqTableParams.java, src/main/java/bio/terra/cli/serialization/userfacing/input/UpdateReferencedGcsObjectParams.java, src/main/java/bio/terra/cli/service/WorkspaceManagerService.java
WSM no longer requires the resource attributes field when updating targeting reference. 
e.g. when updating bucket object from foo to bar within the same object, the bucket name field can be set to null.
=> PF-1271: Update WorkspaceManagerService API call based on WSM API change

src/main/java/bio/terra/cli/businessobject/User.java, src/main/java/bio/terra/cli/service/GoogleOauth.java, src/main/java/bio/terra/cli/service/utils/HttpUtils.java
Before this PR: After `terra auth revoke`, still able to make calls using access token, such as calling WSM api/workspaces/v1 via swagger
After this PR: After `terra auth revoke`, calling api/workspaces/v1 returns 401. Note that it can take up to a minute for the revoke to take effect.
=> [PF-1253] Invalidate refresh/access token when user runs terra auth revoke

src/main/java/bio/terra/cli/businessobject/Resource.java, src/main/java/bio/terra/cli/businessobject/Workspace.java, src/main/java/bio/terra/cli/businessobject/resource/BqDataset.java, src/main/java/bio/terra/cli/businessobject/resource/BqTable.java, src/main/java/bio/terra/cli/businessobject/resource/GcsBucket.java, src/main/java/bio/terra/cli/businessobject/resource/GcsObject.java, src/main/java/bio/terra/cli/command/auth/Status.java, src/main/java/bio/terra/cli/service/WorkspaceManagerService.java
As of https://github.com/DataBiosphere/terra-workspace-manager/pull/443, we no longer need to use the pet SA on the client side to interact with WSM. It's still useful when making calls directly to GCP, though.
=> [PF-1309] Removed use of pet SA to call WSM.

src/test/java/unit/ClientExceptionHandling.java
The `ClientExceptionHandling` test checked for a literal error message from WSM but a recent PR changed that message (https://github.com/DataBiosphere/terra-workspace-manager/pull/550), causing a nightly test failure. This updates the expected message to match behavior.
=> [PF-1297] Update error message in test

build.gradle, src/main/java/bio/terra/cli/app/utils/AppDefaultCredentialUtils.java, src/main/java/bio/terra/cli/businessobject/User.java, src/main/java/bio/terra/cli/command/auth/Login.java, src/main/java/bio/terra/cli/serialization/persisted/PDUser.java, src/main/java/bio/terra/cli/service/GoogleOauth.java
terra auth login currently requires user authenticating through browser oauth flow. 
I added a flag --use-app-default-credentials that allows logging into terra with application default credentials when it is available. If the flag is on but the app default credential is not available, we will still open the browser as a fallback. 
This is to log into terra as the Pet service account when creating a notebook instance to simplify end user's setup.
=> [PF-1333] use ADC when available for log into terra CLI

src/main/java/bio/terra/cli/command/resource/create/GcpNotebook.java
it is unclear if user is not familiar with picoli command options what the input format is for map Command.Options.
=> [PF-1340] clarify how to specify multiple metadata when creating notebook

src/main/java/bio/terra/cli/command/resource/create/GcpNotebook.java
the default metadata are workspace id and server id. Unless specifically override by user input, we should still append those when some arbitray metadata is appended.
=> [PF-1341] When setting metadata to the notebook, still append the default metadata unless specified to be override

build.gradle, src/main/java/bio/terra/cli/businessobject/Workspace.java, src/main/java/bio/terra/cli/service/WorkspaceManagerService.java
A change to `enablePet()` made it return void instead of `String`.  This broke CLI compilation when I upgraded the workspace manager client lib.
=> Fix enable pet call

src/test/java/unit/Workspace.java
Stopgap to work around an issue caused by many leaked workspaces in `dev`. When fetching the workspace list, if there were too many workspaces, the one we care about might not be returned in the first page, as the test expects. Solution for now is to use a much larger `limit` parameter than the default.
=> [PF-1321] increase limit when fetching workspace list

CONTRIBUTING.md, README.md, src/main/java/bio/terra/cli/app/utils/DockerClientWrapper.java, src/main/java/bio/terra/cli/businessobject/Config.java, src/main/java/bio/terra/cli/businessobject/User.java, src/main/java/bio/terra/cli/command/config/set/AppLaunch.java, src/main/java/bio/terra/cli/command/config/set/Image.java, tools/download-install.sh, tools/install-for-testing.sh, tools/install.sh, tools/local-dev.sh
Since we have a config option to run apps locally instead of in the docker container, we technically can install the CLI without docker. This changes mainly the bash installation scripts to make this possible.
Also changed some bash code based on IDE suggestions, primarily around double quoting expanded variables.
=> [PF-1269] installation without Docker support

.github/workflows/tests-nightly.yml, CONTRIBUTING.md, src/test/java/unit/Config.java, src/test/java/unit/Server.java
Verily repo has been running against Verily deployment for a while now.
=> [PF-1289] Stop running nightly tests against Verily deployment

README.md
Before:
```
> gcloud auth application-default login
> terra gsutil ls
gsutil version: 5.6
Mar 14, 2022 2:56:11 PM com.google.auth.oauth2.DefaultCredentialsProvider warnAboutProblematicCredentials
WARNING: Your application has authenticated using end user credentials from Google Cloud SDK. We recommend that most server applications use service accounts instead. If your application continues to use end user credentials from Cloud SDK, you might receive a "quota exceeded" or "API not enabled" error. For more information about service accounts, see https://cloud.google.com/docs/authentication/.
Setting the gcloud project to the workspace project
Updated property [core/project].
gs://melchangbucketwithnounderscore/
gs://terra_39b40817_37d0_4cae_8147_e677490353f9_bucket/
Restoring the original …
```
=> Hide ADC warning, so users won't get confused

CONTRIBUTING.md, README.md, docker/Dockerfile, src/main/java/bio/terra/cli/app/CommandRunner.java, src/main/java/bio/terra/cli/app/DockerCommandRunner.java, src/main/java/bio/terra/cli/app/LocalProcessCommandRunner.java, src/test/java/harness/TestCommand.java, src/test/java/unit/PassthroughApps.java
`gcloud alpha storage` works in local mode. This PR makes it work in Docker mode.
Before:
```
~/terra-cli (main): /usr/local/bin/terra gcloud alpha storage ls
Mar 14, 2022 3:25:27 PM com.google.auth.oauth2.DefaultCredentialsProvider warnAboutProblematicCredentials
WARNING: Your application has authenticated using end user credentials from Google Cloud SDK. We recommend that most server applications use service accounts instead. If your application continues to use end user credentials from Cloud SDK, you might receive a "quota exceeded" or "API not enabled" error. For more information about service accounts, see https://cloud.google.com/docs/authentication/.
Setting the gcloud project to the workspace project
Updated property [core/project].
You do not currently have this command group …
```
=> [PF-1395] Support `gcloud alpha storage` in Docker mode

README.md
CLI defaults to a Broad test environment, which is confusing to real users.
I didn't add the part about "Here's how to talk to Broad production" because there is no Broad prod environment right now, only Verily.
I tried to make it so:
1. Real users won't skip this step
2. CLI developers know to skip this step
=> Add `terra server set` to installation instructions

src/test/java/unit/FineGrainedAccessGcsObjectReference.java, src/test/java/unit/GcsBucketReferenced.java
Now that access checks on reference creation and update have been removed, these tests started failing because of expected failures that turned into successes. Deleted two of them in the interest of saving time, as we already have coverage of updating references.
=> [PF-1428] Fix/remove tests

src/main/java/bio/terra/cli/command/resource/create/GcpNotebook.java
the default metadata fields are now defined in wsm since https://github.com/DataBiosphere/terra-workspace-manager/pull/582.
=> PF-1409: remove default metadata

CONTRIBUTING.md
My Linux desktop was just reimaged. I had to run `sudo chmod 666 /var/run/docker.sock` to get tests to work.
=> Add test troubleshooting tip

.github/workflows/tests-nightly.yml, src/main/java/bio/terra/cli/command/resource/addref/BqDataset.java, src/main/java/bio/terra/cli/command/resource/addref/BqTable.java, src/main/java/bio/terra/cli/command/resource/addref/GcsBucket.java, src/main/java/bio/terra/cli/command/resource/addref/GcsObject.java, src/main/java/bio/terra/cli/command/resource/addref/GitRepo.java, src/main/java/bio/terra/cli/command/resource/create/GcpNotebook.java, src/main/java/bio/terra/cli/command/shared/options/ControlledResourceCreation.java, src/main/java/bio/terra/cli/command/shared/options/ReferenceCreation.java, src/main/java/bio/terra/cli/command/shared/options/ReferencedResourceCreation.java, src/main/java/bio/terra/cli/command/shared/options/ResourceCreation.java, src/test/java/unit/CloneWorkspace.java, src/test/java/unit/GcpNotebookControlled.java, src/test/java/unit/GcsBucketControlled.java
Unlike other parameters, `cloning` has two defaults. For referenced resources it should be `REFERENCE`, and for controlled resources it should be `RESOURCE`.
Also shortened a test job name so that it can fit the whole name + matrix argument in the GHA UI.
=> [PF-1501] Specify correct cloning defaults

tools/local-dev.sh, tools/render-config.sh
We were using a very old version of the `dsde-toolbox`; new one has fix for this issue. [Slack convo](https://broadinstitute.slack.com/archives/CADM7MZ35/p1651596362136939). Also got rid of `set -e`, which kills terminal sessions (and can even close windows) in the event of a crash.
=> [PF-1614] fix crash on M1 chip

src/main/java/bio/terra/cli/businessobject/User.java
This ensures we don't skip the refresh and then have the credentials
expire mid-test or mid-commands.
=> [PF-1620] Consider credentials expired 60 seconds early.

.github/workflows/release-on-pr-merge.yml
Bumper action has been failing recently:
https://github.com/DataBiosphere/terra-cli/actions/workflows/release-on-pr-merge.yml
[This slack thread](https://broadinstitute.slack.com/archives/CADM7MZ35/p1650054683138679) says upgrading action should fix it.
=> Fix bumper action

settings.gradle
This sends build scans to https://gradle-enterprise-prod-helm-cluster.api.verily.com/ instead of scans.gradle.com. Here are scans from both local run and GHA:
@ghale
=> [PF-1335] Gradle Enterprise Trial Navigator Step 1

tools/download-install.sh
Repro
```
cd ~
git clone git@github.com:DataBiosphere/terra-cli.git
cd ~
curl -L https://github.com/DataBiosphere/terra-cli/releases/latest/download/download-install.sh | bash && export SUPPRESS_GCLOUD_CREDS_WARNING=true
```
Now the git repo `~/terra-cli` no longer exists. This PR should fix that.
=> When installing, don't clobber terra-cli/ directory

src/main/java/bio/terra/cli/command/workspace/Update.java, src/test/java/unit/CloneWorkspace.java, src/test/java/unit/Workspace.java, src/test/java/unit/WorkspaceOverride.java
Upon our cml. there are only `resource` and  `workspace` can be updated.
and resource (bq-dataset, bq-table, gcs-bucket, gcs-object, git-repo) are already added --new- in previous tickets.
So in this PR. I focus on add --new- only for `workspace` . it shows:
=> PF-1651: make all update parameters start with --new- (only workspace need here)

.gitignore, src/main/java/bio/terra/cli/command/resource/create/GcpNotebook.java, src/test/java/unit/GcpNotebookControlled.java
Metadata option declaration was using a single string with comma-separated values. We need to use an array of separate strings for this to work.
Added a small test to make sure command is accepted; we can only see the metadata created in the Cloud Console AFAIK.
Also a small .gitignore entry for jenv local file.
=> [PF-1721] Fix Metadata command option

build.gradle, gradle.properties
For Gradle Enterprise trial, we'd like to see how much Test Distribution helps unit tests ([see here](https://gradle-enterprise-prod-helm-cluster.api.verily.com/scans/performance?search.timeZoneId=America/Los_Angeles)). We want a way to only look at unit tests in GE UI. (In GE UI, you can't search on system properties, only tags.)
@ghale
=> [PF-1335] Add gradle test tag

src/main/java/bio/terra/cli/service/ExternalCredentialsManagerService.java, src/main/java/bio/terra/cli/service/WorkspaceManagerService.java
We currently retry timeouts from Sam and GCP APIs, this change also adds retries for timeouts from WSM and ECM client libraries. Unfortunately each client library has its own patterns and exception classes, so the `isRetryable` methods can't be deduplicated very well.
=> [PF-1757] Retry I/O errors from WSM and ECM clients

build.gradle, src/main/java/bio/terra/cli/app/utils/AppDefaultCredentialUtils.java, src/main/java/bio/terra/cli/businessobject/Server.java, src/main/java/bio/terra/cli/businessobject/User.java, src/main/java/bio/terra/cli/serialization/persisted/PDServer.java, src/main/java/bio/terra/cli/serialization/userfacing/UFServer.java, src/main/java/bio/terra/cli/service/DataRepoService.java, src/main/java/bio/terra/cli/service/ExternalCredentialsManagerService.java, src/main/java/bio/terra/cli/service/GoogleOauth.java, src/main/java/bio/terra/cli/service/SamService.java, src/main/java/bio/terra/cli/service/WorkspaceManagerService.java, src/main/java/bio/terra/cli/service/utils/TerraCredentials.java, src/main/resources/servers/verily-autopush.json, src/main/resources/servers/verily-devel.json, src/main/resources/servers/verily-preprod.json, src/main/resources/servers/verily-staging.json, src/main/resources/servers/verily.json, src/test/java/harness/TestUser.java, src/test/java/unit/AuthLoginLogout.java, src/test/java/unit/Workspace.java
This PR adds the ability to optionally authenticate to Terra using JWT ID Tokens instead of opaque Access Tokens, configured at the `Server` level.
This PR also configures Verily `Server` definitions to enable ID Token authentication when calling Terra there.
=> PF-1569: Add Option to use ID Tokens for AuthN in Terra API Calls

build.gradle
With older JNA, we hit an UnsatisfiedLinkError: 
Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: $HOME/Library/Caches/JNA/temp/jna10560848527279309035.tmp
=> Update JNA to 5.11.0 for M1 Macs

CONTRIBUTING.md, build.gradle, src/main/java/bio/terra/cli/businessobject/Resource.java, src/main/java/bio/terra/cli/businessobject/Workspace.java, src/main/java/bio/terra/cli/businessobject/resource/DataSource.java, src/main/java/bio/terra/cli/serialization/persisted/PDWorkspace.java, src/main/java/bio/terra/cli/serialization/persisted/resource/PDDataSource.java, src/main/java/bio/terra/cli/serialization/userfacing/UFResource.java, src/main/java/bio/terra/cli/serialization/userfacing/UFWorkspace.java, src/main/java/bio/terra/cli/serialization/userfacing/UFWorkspaceLight.java, src/main/java/bio/terra/cli/serialization/userfacing/resource/UFDataSource.java, src/main/java/bio/terra/cli/serialization/userfacing/resource/UFGcpNotebook.java, src/main/java/bio/terra/cli/service/WorkspaceManagerService.java, src/test/java/harness/utils/TestUtils.java, src/test/java/harness/utils/WorkspaceUtils.java, src/test/java/unit/DataSourceReferenced.java, src/test/java/unit/Workspace.java
For `terra resource describe`, just print title/short description/version/description. Next PR will print data source resource details (eg GCS bucket).
I changed businessobject `Workspace` to store properties as `Map<String,String>` instead of `Properties`. Reason: I wanted to be able to easily get a property's value (see `Workspace.getProperty()`). For example, I wanted to look up a data source's version, which is stored in `terra-version` property.
```
~/terra-cli (mc/data-source-resource $): terra resource list
NAME                            RESOURCE TYPE         STEWARDSHIP TYPE      DESCRIPTION
1000-genomes-ref                DATA_SOURCE           REFERENCED            (unset)
hello_world                     AI_NOTEBOOK           CONTROLLED            (unset) …
```
=> [PF-1742] Add DATA_SOURCE resource

build.gradle
Per gradle discussion, I'm adding this plugin to start tracking test flakes and automatically retry some. This plugin will retry failing tests up to twice, which should reduce the number of times we manually rerun tests on PRs.
This covers up test flakiness but doesn't fix it, if we want shorter PR/nightly tests we'll still need to actually fix the causes of failure. The flake data from this plugin should help, though.
=> [PF-1513] Add gradle test retry plugin

build.gradle, src/main/java/bio/terra/cli/command/resource/Resolve.java, src/test/java/harness/TestCommand.java, src/test/java/unit/BqDatasetControlled.java, src/test/java/unit/BqDatasetReferenced.java, src/test/java/unit/BqTableReferenced.java, src/test/java/unit/GcpNotebookControlled.java, src/test/java/unit/GcsBucketControlled.java, src/test/java/unit/GcsBucketReferenced.java, src/test/java/unit/GcsObjectReferenced.java, src/test/java/unit/GitRepoReferenced.java
terra resolve --name=foo_bucket --format=json
{"foo_bucket":"<project-id>/<bucket_name>"}
This command does not change by this PR: terra resolve --name=foo_bucket
project-id/bucket-name
in the following PR where i implement terra resolve --name=foo_datasource
it will be a JSONArray of JSONObjects
[
{"foo_bucket":"<project-id>/<bucket_name>"},
{"bar_dataset":"<path-to-dataset>"}
]
=> [PF-1827] resolve return a json formatted string

src/main/java/bio/terra/cli/serialization/userfacing/UFWorkspaceLight.java, src/main/java/bio/terra/cli/serialization/userfacing/resource/UFDataSource.java, src/test/java/unit/DataSourceReferenced.java
```
~/terra-cli (mc/data-source-resource $): terra resource describe --name=1000-genomes
Title:			1000 Genomes Phase 3
Short description:	The genomes of more than a thousand anonymous participants from a number of different ethnic groups were analyzed and made publicly available.
Version:		Phase 3
Resources:
NAME                  RESOURCE TYPE         DESCRIPTION
gcs-folder            GCS_OBJECT            (unset)
pedigree              BQ_TABLE              (unset)
phase-3-variants      BQ_TABLE              (unset)
sample_info           BQ_TABLE              (unset)
~/terra-cli (mc/data-source-resource $): terra resource describe --name=1000-genomes --format=json
{
"id" : "62639f59-4cde-487a-b1ca-49b70d6a5d28",
"name" : "1000-genomes",
"description" : null,
"resourceType" : …
```
=> [PF-1742] Show data source resources in `terra resource describe`

build.gradle
I thought we could have the `retry` block inside the `test` task since `runTestsWithTask` has type `Test`, but it looks like we never actually retried tests.
Tested this locally, the new configuration will actually retry tests as expected.
=> [PF-1513] Move test retry config inside runTestsWithTag

src/main/java/bio/terra/cli/app/LocalProcessCommandRunner.java
In notebook post-startup script, `terra git clone --all` failed with:
```
2022-07-21 19:24:23.529 UTC [main] ERROR bio.terra.cli.command.Main - An unexpected error occurred in java.lang.NullPointerException: null
java.lang.NullPointerException: null
at bio.terra.cli.app.LocalProcessCommandRunner.runToolCommandImpl(LocalProcessCommandRunner.java:59)
at bio.terra.cli.app.CommandRunner.runToolCommand(CommandRunner.java:83)
at bio.terra.cli.app.CommandRunner.runToolCommand(CommandRunner.java:50)
at bio.terra.cli.command.app.passthrough.Git.cloneGitRepoResource(Git.java:76)
at bio.terra.cli.command.app.passthrough.Git.lambda$executeImpl$1(Git.java:51)
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
at …
```
=> Fix tool commands in local process mode

src/main/java/bio/terra/cli/serialization/userfacing/resource/UFDataCollection.java
It a rare case but when it happens, we don't want to just throw NPE. createdate and lastupdatedate are not required field in the workspaceDescription.
=> [PF-1859] created date and last udpated date can be null

.github/workflows/tests-nightly.yml, src/main/java/bio/terra/cli/businessobject/Context.java
#282 began storing unit test logs in a different place, which broke the nightly test workflow's log uploading step. Additionally, it mis-handled the `CONTEXT_DIR_OVERRIDE_NAME` by combining filepaths via string concatenation, which caused problems depending on whether the provided value had a trailing `/`. Sorry about that!
Working nightly run from this branch: https://github.com/DataBiosphere/terra-cli/actions/runs/2721117397
=> [PF-1842] Fix nightly test action logs

src/main/java/bio/terra/cli/command/resource/Resolve.java
Before:
```
~/terra-workspace-manager (mc/pandas_gbq): terra resolve --name=1000-genomes
pedigree: bigquery-public-data.human_genome_variants.1000_genomes_pedigree
gcs-folder: gs://genomics-public-data/1000-genomes-phase-3
phase-3-variants: bigquery-public-data.human_genome_variants.1000_genomes_phase_3_variants_20150220
melissachang-terra-example-notebooks: git@github.com:melissachang/terra-example-notebooks.git
sample_info: bigquery-public-data.human_genome_variants.1000_genomes_sample_info
```
After:
```
~/terra-cli (mc/resolve): terra resolve --name=1000-genomes
NAME                                      PATH
pedigree                                  bigquery-public-data.human_genome_variants.1000_genomes_pedigree
gcs-folder                               …
```
=> [PF-1743] For `terra resolve` data collection, print table

src/main/java/bio/terra/cli/app/utils/LocalProcessLauncher.java, src/main/java/bio/terra/cli/command/app/passthrough/Git.java
`terra git clone --all` gives this error for my devel workspace:
> /tmp: terra git clone --all
>Setting the gcloud project to the workspace projectUpdated property [core/project].Cloning into 'terra-example-notebooks'...Restoring the original gcloud project configuration: terra-vdevel-buoyant-plum-9341Updated property [core/project].Setting the gcloud project to the workspace projectUpdated property [core/project].fatal: destination path 'terra-example-notebooks' already exists and is not an empty directory.Git clone for git@github.com:melissachang/terra-example-notebooks.git failed
This was because a git repo was being cloned twice.
- My workspace had a git repo
- My workspace had a data collection which had the same git repo
I also fixed the tool output in local mode; newlines are now …
=> Don't clone duplicate git repos

src/main/java/bio/terra/cli/command/group/ListUsers.java
Before:
```
~/terra-cli (mc/group-list-users $): terra group list-users --name=developer-admins-devel
EMAIL                                                                                  POLICIES
XXXXX@google.com                                                                       [ADMIN]
XXXXXXXXXXX@google.com                                                                 [ADMIN]
XXXXX@google.com                                                                       [ADMIN]
```
After:
```
~/terra-cli (mc/group-list-users $): terra group list-users --name=developer-admins-devel
EMAIL                           POLICIES
XXXXX@google.com                [ADMIN]
XXXXXXXXXXX@google.com          [ADMIN]
XXXXX@google.com                [ADMIN]
```
=> Make `terra group list-users` table not so wide

.github/workflows/cleanup-test-user-workspaces.yml, .github/workflows/tests-nightly.yml, .github/workflows/tests-on-pr-push-and-merge.yml
The `joschi/setup-jdk@v2` Github action is deprecated and the recommendation is to move to the official github setup-java action with the `temurin` distribution: see https://github.com/joschi/setup-jdk#-notice
=> [PF-1731] Replace Java setup action

src/main/java/bio/terra/cli/app/CommandRunner.java, src/main/java/bio/terra/cli/businessobject/Resource.java, src/main/java/bio/terra/cli/businessobject/resource/BqDataset.java, src/main/java/bio/terra/cli/businessobject/resource/BqTable.java, src/main/java/bio/terra/cli/businessobject/resource/GcpNotebook.java, src/main/java/bio/terra/cli/businessobject/resource/GcsBucket.java, src/main/java/bio/terra/cli/businessobject/resource/GcsObject.java, src/main/java/bio/terra/cli/businessobject/resource/GitRepo.java, src/test/java/unit/DataCollectionReferenced.java, src/test/java/unit/PassthroughApps.java
WSM allows dashes:
https://cs.github.com/DataBiosphere/terra-workspace-manager/blob/4eabe67ee705645c85cb9f522e739fb8b8a77228/service/src/main/java/bio/terra/workspace/service/resource/ResourceValidationUtils.java?q=resource_name#L103
CLI currently doesn't. Change CLI to match WSM.
Before:
```
~/terra-cli (mc/allow-dash): terra resource create gcp-notebook --post-startup-script=gs://melchangbucketwithnounderscore/post-startup.sh --name="resource-name-dash"
Invalid resource name specified. Name must be 1 to 1024 alphanumeric characters, underscores, and dashes and must not start with a dash or underscore.
```
After:
```
~/terra-cli (mc/allow-dash): terra resource create gcp-notebook --post-startup-script=gs://melchangbucketwithnounderscore/post-startup.sh --name="resource-name-dash" …
```
=> [PF-1750] Alllow dashes in resource name

src/main/resources/servers/all-servers.json, src/main/resources/servers/broad-wsmtest.json
To run post-startup script test in wsm nightly, we need to have the cli to be able to point to the wsmtest server.
=> [PF-1660] Add a new server for wsmtest

src/test/java/unit/GcsBucketControlled.java
This ticket solves 2 issues after the PF-1750 auto-generation cloud-native id.
Both changes in the unit test GcsBucketControlled.java. 
-  the generated bucket name is not contain "bucket". It contains the originalName.toLowerCase(). (the original name does not have any character, so only to lower case is enough)
- we do not allow the same bucket name in the same workspace. I changed the bucket name is unique. (feel a little confused each unit test, the resource will be delete in the end, it could not have same bucket name, maybe rerun the whole unit test can solve, I still change the name unique in order to be clear with each unit test with their individual specified bucket name.)
=> fix the autoname bucket name bug

src/main/java/bio/terra/cli/service/WorkspaceManagerService.java
Flaky failure: https://github.com/verily-src/terra-tool-cli/runs/8211018493?check_suite_focus=true
GCS bucket deletiong flight took 43 seconds to complete. By default, we poll for 15 seconds. Increase polling time to 1 minute.
=> Increase polling time for deleting GCS bucket

src/main/java/bio/terra/cli/service/WorkspaceManagerService.java
We retry for 2 mins. For one of the flakes last night, cloud context creation took 2 mins 28 sec. So increase to 3 mins.
Also:
- Move constants inline, so I don't have to scroll to top of file to see values
- We were retrying clone workspace for 1 hr, which seems excessive. Changed to 5 min
=> For cloud context creation, retry for 3 mins instead of 2 mins

src/main/java/bio/terra/cli/businessobject/Context.java
The `cleanupTestUserWorkspaces` uses the CLI Test Harness to call commands outside of a test context.  This leads to an NPE when a NULL String is passed to the `Path.resolve()` method.
=> [PF-1998] Check that 'test worker' property is present before using.

README.md
I had always assumed Terra groups worked this way, but didn't see any documentation in the CLI to confirm/deny. Fortunately we were able to test and confirmed that it does indeed work this way.
Created this because tests weren't running in #323
=> Add example group usage to README

.github/workflows/release-on-pr-merge.yml, .github/workflows/tests-on-pr-push-and-merge.yml
Issue - If changeset only has .md files (readme.md for example) the PR check (github workflow) does not report the status as success  skipped, thus leading to a PR that can't be merged
As a workaround remove this config for now
Further work will be carried out in https://broadworkbench.atlassian.net/browse/PF-2048
=> [PF-2049] terra-cli: Remove paths ignore from Github workflows

.github/workflows/tests-on-pr-push-and-merge.yml
Guang noticed that the lint check fails with her PR that uses a new java api in the PR https://github.com/DataBiosphere/terra-cli/pull/322.
=> PF-1554: set java jdk to 17 for lint and static test

src/test/java/harness/CRLJanitor.java
We had originally left this higher in case developers found it helpful for debugging, but that hasn't materialized so I'm bringing this down to 6h.
=> [PF-2086] Have Janitor clean up test workspaces after 6h

.github/workflows/release-on-pr-merge.yml
This action recently failed due to what looks like a Java version issue (https://github.com/DataBiosphere/terra-cli/actions/runs/3170417202).
=> Use java 17 in release-on-pr-merge action

src/test/java/harness/utils/CleanupTestUserWorkspaces.java
I didn't realize this script only cleaned up a max of 500 users, that explains why we've had to re-run it more frequently than expected.
=> Cleanup 500 users at a time

build.gradle, gradle/test.gradle, settings.gradle, src/main/java/bio/terra/cli/businessobject/Context.java, src/main/java/bio/terra/cli/command/shared/options/CloningInstructionsForUpdate.java, src/main/resources/configs/generate-cromwell-config.sh, src/test/resources/testscripts/CreateWorkspace.sh, src/test/resources/testscripts/DeleteWorkspace.sh, tools/build-docker.sh, tools/create-break-glass-bq.sh, tools/download-install.sh, tools/install-for-testing.sh, tools/install.sh, tools/local-dev.sh, tools/publish-docker.sh, tools/publish-release.sh, tools/render-config.sh, tools/setup-test-users.sh
Problem statement - Terra CLI needs java 17 installed. There is no check during cli installation, but execution fails
Fix - add a check for java version during installation
with this change, install will fail if Java is set to <17. 
terra command would still fail if the java version is changed after install. Keeping this use case out of scope for now
Testing  - install fails with java set to version 11
```
clicheck-test >> ls
download-install.sh
clicheck-test >> jenv versions
...
* 11.0 (set by /Users/dexamundsen/clicheck-test/.java-version)
...
clicheck-test >> java --version
openjdk 11.0.16.1 2022-07-19 LTS
OpenJDK Runtime Environment Zulu11.58+23-CA (build 11.0.16.1+1-LTS)
OpenJDK 64-Bit Server VM Zulu11.58+23-CA (build 11.0.16.1+1-LTS, mixed mode)
clicheck-test >> …
```
=> [PF-2101] Check java version in CLI download-install.sh

src/main/java/bio/terra/cli/app/CommandRunner.java
Source email address may be mixed case.
People and applications would expect consistent values.
Fixes flaky test added in #320 .
=> [PF-1955] Explicitly lower case the TERRA_USER_EMAIL value.

src/main/java/bio/terra/cli/app/CommandRunner.java, src/main/java/bio/terra/cli/businessobject/User.java, src/main/java/bio/terra/cli/businessobject/WorkspaceUser.java
This way, callers of User.getEmail() or WorkspaceUser.getEmail() don't have to lower-case themselves, which is error-prone.
Ran PassthroughApps.workspaceEnvVars multiple times, still not flaky.
=> [PF-2138] Lower-case email stored in User, WorkspaceUser

src/main/java/bio/terra/cli/command/workspace/List.java
The `terra workspace list` could not show full id because it long. Change the column size from 36 to 40 then manually test it. 
**Before**
```
ID                                    NAME                            GOOGLE PROJECT                  DESCRIPTION                                                           
a-6bc4a502-8600-4449-b224-0104d80...  (unset)                         terra-vdevel-speedy-lemon-8435  (unset)                                 
clonetestname                         (unset)                         terra-vdevel-cold-lime-8223     (unset)     
```
**After**
```
ginay-macbookpro:terra-cli ginay$ terra workspace list
ID                                        NAME                            GOOGLE PROJECT                  DESCRIPTION …
```
=> [PF-1755] `terra workspace list` long workspace id is  truncated 

docker/Dockerfile
Problem statement - Standard eclipse temurin images potentially have app-security concerns
Fix - use the broad app-security-approved images from https://github.com/broadinstitute/dsp-appsec-blessed-images
No further checks were performed since the major version is the same, minor version is a downgrade
=> [PF-940] Use broad-appsec-blessed JRE image

README.md
I believe this was a cut & paste error in an earlier edit of the README.
=> fix terra 'group' command error

gradle/test.gradle, src/main/java/bio/terra/cli/utils/Version.java
Background:
- This PR comes from the ticket [PF-2268](https://broadworkbench.atlassian.net/browse/PF-2268). The [PF-2174](https://broadworkbench.atlassian.net/browse/PF-2174). 
- The error only happens in Verily server. and shows the current version is null. see [details](https://scans.gradle.com/s/tt2z6g6zxrn4w/tests/overview)
- We dive deep into the code, and find the reason is https://github.com/DataBiosphere/terra-cli/blob/main/src/main/java/bio/terra/cli/app/utils/VersionCheckUtils.java#L65 verily server set the oldest version, so it could not go into the if statement there, when the current version is null. then in L72 it could not parse. 
The way for solve the problem is which learn from `Config.java` https://github.com/DataBiosphere/terra-cli/blob/main/src/main/java/bio/terra/cli/b …
=> [PF-2268] fix the currentVersion is null cause NPE 

src/main/java/bio/terra/cli/businessobject/User.java, src/main/java/bio/terra/cli/businessobject/resource/GcpNotebook.java, src/main/java/bio/terra/cli/command/notebook/Start.java, src/main/java/bio/terra/cli/command/notebook/Stop.java, src/main/java/bio/terra/cli/command/shared/options/NotebookInstance.java, src/main/java/bio/terra/cli/service/AmazonCloudStorage.java, src/main/java/bio/terra/cli/service/SamService.java, src/main/java/bio/terra/cli/service/WorkspaceManagerService.java, src/main/resources/servers/all-servers.json
test - 
```
terra-cli (dexamundsen/mc-204) >> terra workspace set --id=test-ws-3
Workspace successfully loaded.
ID:                test-ws-3
Name:              
Description:       
AWS account:       639879951631
Landing Zone Id:   9153e570-9616-6577-4522-16b49993e2d5
Cloud console:     https://639879951631.signin.aws.amazon.com/console/
Created:           2022-11-30
Last updated:      2022-12-01
terra-cli (dexamundsen/mc-204) >> terra resource list
NAME                            RESOURCE TYPE         STEWARDSHIP TYPE      DESCRIPTION                             
note-1                          AWS_SAGEMAKER_NOT...  CONTROLLED            (unset)                                 
note-2                          AWS_SAGEMAKER_NOT...  CONTROLLED            (unset) …
```
=> [TERRA-204] Add support in CLI to fetch AWS credentials from WSM

README.md, src/main/java/bio/terra/cli/app/CommandRunner.java, src/main/java/bio/terra/cli/app/LocalProcessCommandRunner.java, src/main/java/bio/terra/cli/command/SshKey.java, src/main/java/bio/terra/cli/command/user/sshkey/Add.java, src/main/java/bio/terra/cli/command/user/sshkey/Generate.java, src/test/java/unit/SshKeyPair.java
There is a user friction when a user created an AI notebook for the first time and didn't set up an ssh key. Or they regenerate a new ssh key and deleted the old one from their github account after a notebook is already created. 
Right now there's no easy way to get and add the new terra ssh key to the notebook.
Adding a `terra user ssh-key add` command to get and save the key and add it to the ssh-agent.
Also did a refactor to achieve the same with `terra user ssh-key generate --save-to-file`.
```
yuhuyoyo-macbookpro3% terra user ssh-key add
Saved the terra ssh key to ~/.ssh/terra_id_rsa and ~/.ssh/terra_id_rsa.pub
Agent pid 39723
Identity added: /Users/yuhuyoyo/.ssh/terra_id_rsa (/Users/yuhuyoyo/.ssh/terra_id_rsa)
ssh-rsa <my-key>
```
=> PF-2376: add a ssh-key add command 

src/main/java/bio/terra/cli/app/CommandRunner.java, src/main/java/bio/terra/cli/businessobject/Resource.java, src/main/java/bio/terra/cli/businessobject/User.java, src/main/java/bio/terra/cli/businessobject/Workspace.java, src/main/java/bio/terra/cli/businessobject/resource/BqDataset.java, src/main/java/bio/terra/cli/businessobject/resource/BqTable.java, src/main/java/bio/terra/cli/businessobject/resource/GcpNotebook.java, src/main/java/bio/terra/cli/businessobject/resource/GcsBucket.java, src/main/java/bio/terra/cli/businessobject/resource/GcsObject.java, src/main/java/bio/terra/cli/businessobject/resource/GitRepo.java, src/main/java/bio/terra/cli/command/app/passthrough/Git.java, src/main/java/bio/terra/cli/command/cromwell/GenerateConfig.java, src/main/java/bio/terra/cli/command/resource/List.java, src/main/java/bio/terra/cli/command/resource/ListTree.java, src/main/java/bio/terra/cli/command/shared/options/NotebookInstance.java, src/main/java/bio/terra/cli/command/workspace/BreakGlass.java, src/main/java/bio/terra/cli/command/workspace/DeleteProperty.java, src/main/java/bio/terra/cli/command/workspace/List.java, src/main/java/bio/terra/cli/command/workspace/SetProperty.java, src/main/java/bio/terra/cli/command/workspace/Update.java, src/main/java/bio/terra/cli/serialization/persisted/PDWorkspace.java, src/main/java/bio/terra/cli/serialization/userfacing/UFWorkspace.java, src/main/java/bio/terra/cli/serialization/userfacing/UFWorkspaceLight.java
This is to avoid stale cache.
Only cache workspace id, user facing id, googleProjectId, cloudPlatform which are not changeable once a workspace is created.
`googleProjectId` is used in many app execute run so it's worth caching it for optimization reasons. 
```
"workspace" : {
"uuid" : "cf70600a-bddd-47d4-b34a-736edfda7747",
"userFacingId" : "yu-workspace-2",
"googleProjectId" : "terra-vdevel-strong-berry-3842",
"cloudPlatform" : "GCP"
},
```
=> PF-1889: Do not cache workspace in context.json

.github/workflows/tests-nightly.yml, .github/workflows/tests-on-pr-push-and-merge.yml, CONTRIBUTING.md, gradle/test.gradle, settings.gradle, src/test/java/harness/TestCommand.java, src/test/java/harness/TestConfig.java
Add quietConsole option to tests
Problem statement - at time the console output of PR checks (especially unit tests) run into 50k+ lines. This is difficult to debug and the page load is often slow. 
Solution - add an option to suppress STDIN and STDOUT of the test commands from being printed on the console. 
No changes to stderr 
Testing -- 
```
terra-cli (dexamundsen/pf-2438) >> ./gradlew :runTestsWithTag --tests "unit.Workspace.statusDescribeListReflectDelete" -PtestTag=unit -PquietConsole
...
Workspace STANDARD_OUT
17:12:37.218 [Test worker] DEBUG harness.TestConfig - Reading test config from testconfigs/broad.json
COMMAND: config set logging --console --level=OFF
17:12:37.525 [Test worker] WARN bio.terra.cli.utils.UserIO - Printing setup called multiple times. This is expected when …
```
=> [PF-2438] Add quietConsole option to tests

tools/local-dev.sh
Similar to the check we have in [download-install.sh](https://github.com/DataBiosphere/terra-cli/blob/main/tools/download-install.sh).
Some questions that may come up:
> This code looks almost exactly copy-pasted from `download-install.sh`. Why not move it to a common util script?
In the main Readme we suggest users call the download-install script by running `curl -L https://github.com/DataBiosphere/terra-cli/releases/latest/download/download-install.sh | bash`. Moving the common code out to a utility script would break that flow.  
> Why isn't the code exactly copy-pasted? What changes did you make?
In the failure case, instead of doing `exit 1` I do a `return 1`. This is because the usage of this script is `source local-dev.sh`, which means we run it in the current shell. I don't want …
=> Check Java version in local-dev.sh

src/main/java/bio/terra/cli/businessobject/Workspace.java, src/main/java/bio/terra/cli/command/workspace/List.java, src/main/java/bio/terra/cli/serialization/userfacing/UFWorkspaceLight.java, src/main/java/bio/terra/cli/service/WorkspaceManagerService.java, src/main/java/bio/terra/cli/service/utils/CrlUtils.java, src/test/resources/testscripts/NextflowRnaseq.sh
- Fix `workspace list` functionality. Previously, the CLI would make a `get workspace` call for each item in the list due to the way we serialize them, despite all the necessary information already being available. This could cause failures on multithreaded test runs if a workspace was deleted between the `list workspaces` and following `get workspace` call. This also saves us (potentially) several hundred WSM calls per `workspace list` command for real users as well as tests, which is nice.
- Add a wait after creating a bucket in `NextflowRnaseq` test script to allow bucket permissions to propagate
- Decrease polling frequency from 30s to 1m without changing total duration. We're suspicious that more frequent polling may be poisoning caches, but this isn't well established yet.
=> [PF-2333] More test fixes

tools/setup-test-users.sh
- read test users from test config instead of hardcoded values in setup-test-users. 
- no need to rename the util script since this no longer is tied to an instance (broad vs other). 
testing -- 
```
terra-cli (dexamundsen/pf-1339) >> ./tools/setup-test-users.sh test1 test2
Terra ->  /Users/dexamundsen/github/databiosphere/terra-cli/build/install/terra-cli/bin/terra
terra-cli (dexamundsen/pf-1339) >> cd tools; PWD; ./setup-test-users.sh test1 test2
/Users/dexamundsen/github/databiosphere/terra-cli/tools
ERROR: Script must be run from top-level directory 'terra-cli/'
tools (dexamundsen/pf-1339) >> PWD; ./setup-test-users.sh test1 test2 /Users/dexamundsen/github/databiosphere/terra-cli/build/install/terra-cli/bin/terra
/Users/dexamundsen/github/databiosphere/terra-cli/tools
Terra -> …
```
=> [PR-1339] read test users from test config

src/main/java/bio/terra/cli/command/server/List.java, src/test/java/harness/TestConfig.java, src/test/java/harness/baseclasses/ClearContextUnit.java, src/test/java/harness/baseclasses/SingleWorkspaceUnit.java
- Minor change: move platformStorageName to base class in unit tests
- Reason: 1) Use gcs-bucket as the default storage type, aligning with the default platform (GCP). prior to the change, this is not set and an exception is thrown. 
- Add JsonIgnoreProperties to testConfig.java to ignore unknown properties in the test config file
=> move platformStorageName to base class in unit tests

.github/workflows/tests-on-pr-push-and-merge.yml
Only run PR checks when the PR targets main/master branch
currently, all PRs (irrespective of the branch they target) automatically trigger PR checks. This is unnecessary and may cause the checks to be queued up on GitHub runner.
=> [PF-2478] Only run checks when PR targets 'main' branch

src/main/java/bio/terra/cli/cloud/gcp/GoogleOauth.java, src/main/resources/verily_secret.json
- Must redirect to an acutal URI, in this case a TVC URI for Verily's config.
- New ClientID (type web) is required in order to support redirect_uri.
context: https://developers.google.com/identity/protocols/oauth2/resources/oob-migration
=> Fix OOB auth flow in cli.

src/main/java/bio/terra/cli/command/SshKey.java, src/main/java/bio/terra/cli/command/user/sshkey/Add.java, src/main/java/bio/terra/cli/command/user/sshkey/Generate.java, src/main/java/bio/terra/cli/command/user/sshkey/Get.java
I created the PR to fix a typo in a description, but while I was in there I thought I would make the descriptive text a bit more consistent as well.
=> fix typo, make the ssh-key command descriptive text more consistent

src/main/java/bio/terra/cli/businessobject/Resource.java, src/main/java/bio/terra/cli/businessobject/Workspace.java
Flexible resources are breaking `terra resource list` for workspaces that contain them. Lets omit resources unsupported by CLI instead of throwing an error.
https://broadworkbench.atlassian.net/browse/PF-2661
=> [PF-2661] - Omit unsupported resources from resource list

.github/workflows/release-on-pr-merge.yml, .github/workflows/tests-nightly.yml, .github/workflows/tests-on-pr-push-and-merge.yml, settings.gradle, src/main/resources/broad_secret.json, src/main/resources/verily_secret.json, tools/client-credentials.sh, tools/publish-release.sh, tools/render-config.sh
- Remove client_id and client_secret from secrets file
- Fetch these values from env during release publish and insert into secrets file
```
>>  ./tools/client-credentials.sh "src/main/resources/broad_secret.json" $BROAD_CLIENT_ID $BROAD_CLIENT_SECRET
>> terra-cli (dexamundsen/terra-495) >> ./tools/publish-release.sh dex-test-release
Downloaded the prerelease and verified that json files include client credentials.
>> ./tools/render-config
```
- Credentials are needed in PR tests, a successful PR check implies this is reflected in CI/CD runs
=> [TERRA-495], [PF-2631] Remove client_id and client_secret

tools/render-config.sh
Local dev needs verily client_creds, fetch it in the render_config script, that is called from local_dev script
=> Fetch verily client secret in for render_config (broad script) for local dev

src/main/java/bio/terra/cli/command/app/passthrough/Git.java, src/test/java/unit/GcpPassthroughApps.java
Instead of the git repo name itself.
=> [PF-2629] - Use resource name as the cloned repo directory name

.github/workflows/tests-nightly.yml, .github/workflows/tests-on-pr-push-and-merge.yml
In #478, I added the wrong platform tag, as it's actually case-sensitive. The GHA is currently skipping tests tagged with `unit-gcp`
=> [PF-2113] Fix test tag error

src/main/java/bio/terra/cli/businessobject/Workspace.java, src/main/java/bio/terra/cli/command/workspace/Set.java, src/main/java/bio/terra/cli/serialization/userfacing/UFWorkspaceLight.java, src/test/java/unit/Workspace.java
I've recently found several scenarios where I needed to resort to using direct WSM calls (Swagger UI by port-forwarding or curl) to get Workspace UUID's.
Issue [TERRA-575](https://verily.atlassian.net/browse/TERRA-575) exposes a specific case where not being able to resolve a workspace UUID to a workspace user-facing ID causes an issue.  
In AWS, we tag resources with the workspace UUID, for IAM, grouping, and (eventually) billing purposes.  In the SageMaker notebook instance controlled resource use case, we want to use this tag to automate configuration of the Terra CLI in the startup script.  This is currently not possible with the `terra set workspace` command.
This PR addresses these issues by:
* Adding `uuid` to the JSON output of `terra workspace [list|describe]`.  This is already …
=> TERRA-575: Allow 'set workspace' by UUID, expose workspace UUID in JSON.

.github/workflows/tests-nightly.yml, .github/workflows/tests-on-pr-push-and-merge.yml, src/main/java/bio/terra/cli/businessobject/resource/AwsSageMakerNotebook.java, src/main/java/bio/terra/cli/command/Notebook.java, src/main/java/bio/terra/cli/command/notebook/Launch.java, src/main/java/bio/terra/cli/command/resource/Resolve.java, src/main/java/bio/terra/cli/service/WorkspaceManagerServiceAws.java, src/test/java/unit/AwsSageMakerNotebookControlled.java
- New  subcommand to get Notebook proxyUrl
- connected test
Manual test - 
```
terra-cli (dexamundsen/terra-564) >> terra notebook launch --name=dex-notebook-516-1
<verified classic view url>
terra-cli (dexamundsen/terra-564) >> terra notebook launch --name=dex-notebook-516-1 --proxy-view=JUPYTERLAB
<verified lab view url>
terra-cli (dexamundsen/terra-564) >> terra notebook stop --name=dex-notebook-516-1
Notebook instance stopped
terra-cli (dexamundsen/terra-564) >> terra notebook launch --name=dex-notebook-516-1
Cannot launch notebook instance: Expected notebook instance status is [InService] but current status is Stopped
```
=> [TERRA-564] Add subcommand to get Notebook proxyUrl

src/main/java/bio/terra/cli/businessobject/resource/AwsSageMakerNotebook.java, src/main/java/bio/terra/cli/command/notebook/Start.java, src/main/java/bio/terra/cli/command/resource/create/AwsSageMakerNotebook.java, src/main/java/bio/terra/cli/serialization/userfacing/resource/UFAwsSageMakerNotebook.java, src/main/java/bio/terra/cli/service/WorkspaceManagerService.java, src/main/java/bio/terra/cli/service/WorkspaceManagerServiceAws.java, src/test/java/harness/utils/ResourceUtils.java, src/test/java/unit/AwsS3StorageFolderControlled.java, src/test/java/unit/AwsSageMakerNotebookControlled.java
- Return from create / start aws commands immediately
- describe resource may be used to check status
- No changes at this time to delete, stop commands
- Start command behaviors are now consistent b/w AWS and GCP. These are fairly quick to complete (under 5 min). Further stop / delete confirmation is likely important for the user since it mat otherwise lead to user being charged
- Also included: minor UT fixes
locat test - 
```
terra-cli (dexamundsen/terra-578) >> terra resource create sagemaker-notebook --name=dex-notebook-517-5
Creating notebook instance. It may take a few minutes before it is available
terra-cli (dexamundsen/terra-578) >> terra resource list
NAME                            RESOURCE TYPE         STEWARDSHIP TYPE      DESCRIPTION                             
… …
```
=> [TERRA-578] Return from create / start aws commands immediately

src/main/java/bio/terra/cli/command/workspace/ConfigureAws.java
* `workspace configure-aws` generates configs for SageMaker notebook resources.
* Notebook config file uses UUID instead of workspace name to work better with automation, no longer needs namespacing by server name.
Result:
```
$ eval $(terra workspace configure-aws)
$ echo ${AWS_CONFIG_FILE}
/Users/jczerk/.terra/aws/3d83d56b-adde-4243-9b9d-xxxxxxxxxxxx.conf
$ aws --profile notebook-xxxxxxxxxx sagemaker describe-notebook-instance --notebook-instance-name notebook-xxxxxxxxxx
{
"NotebookInstanceArn": "arn:aws:sagemaker:us-east-1:000000000000:notebook-instance/notebook-xxxxxxxxxx",
"NotebookInstanceName": "notebook-xxxxxxxxxx",
"NotebookInstanceStatus": "Stopped",
...
```
=> Add SageMaker notebook resource to generated AWS config, use UUID for filename.

.github/workflows/release-on-pr-merge.yml, .github/workflows/tests-nightly.yml, .github/workflows/tests-on-pr-push-and-merge.yml, settings.gradle, src/main/java/bio/terra/cli/cloud/gcp/GoogleOauth.java, src/main/resources/broad_secret.json, src/main/resources/servers/broad-dev-cli-testing.json, src/main/resources/servers/broad-dev-local-sam.json, src/main/resources/servers/broad-dev-local-wsm.json, src/main/resources/servers/broad-dev-mmedlock.json, src/main/resources/servers/broad-dev-zloery.json, src/main/resources/servers/broad-dev.json, src/main/resources/servers/broad-wsmtest.json, src/main/resources/servers/verily-autopush.json, src/main/resources/servers/verily-devel.json, src/main/resources/servers/verily-mc-feature-dev.json, src/main/resources/servers/verily-preprod.json, src/main/resources/servers/verily-staging.json, src/main/resources/servers/verily.json, src/main/resources/verily_secret.json, src/test/java/harness/TestBashScript.java, src/test/java/harness/baseclasses/ClearContextIntegration.java, tools/client-credentials.sh, tools/render-config.sh
Test with published version 
```
temp >> curl -L https://github.com/DataBiosphere/terra-cli/releases/download/dexamundsen-bench-530/download-install.sh | bash && export SUPPRESS_GCLOUD_CREDS_WARNING=true
….
temp >> ./terra server status
Current server: broad-dev-cli-testing (Broad development environment for CLI testing. More stable and updated less frequently than the main development environment.)
Server status: OKAY
temp >> ./terra auth status
NO USER LOGGED IN
temp >> ./terra auth login
Please open the following address in your browser:
…
Attempting to open that address in the default browser now...
Login successful: dexamundsen@google.com
temp >> ./terra server set --name=verily-devel
Switching the server will clear the current login credentials and workspace. Are you sure you want …
```
=> [BENCH-530] Render client id / secrets to files in rendered folder

.github/workflows/tests-on-pr-push-and-merge.yml, src/main/java/bio/terra/cli/command/notebook/Start.java, src/main/java/bio/terra/cli/command/resource/OpenConsole.java, src/main/java/bio/terra/cli/service/WorkspaceManagerServiceAws.java, src/main/java/bio/terra/cli/utils/UserIO.java, src/main/resources/verily_secret.json, src/test/java/unit/AwsS3StorageFolderControlled.java, src/test/java/unit/AwsSageMakerNotebookControlled.java
[BENCH-655] Open console link in browser if supported
Testing - 
```
>> terra config set browser AUTO
Browser launch mode for login is AUTO (UNCHANGED).
>> terra resource open-console --name=dex-s3-519-1 
Please open the following address in your browser:
<url>
Attempting to open that address in the default browser now...
<verified that link opened in default browser>
>> terra config set browser MANUAL
Browser launch mode for login is MANUAL (CHANGED).
>> terra resource open-console --name=dex-s3-519-1 
Please open the following address in your browser:
<url>
<no browser window opened>
```
[BENCH-660] - display message that notebook is started if start is requested when notebook is already in service
AWS tests local run successful
=> [BENCH-655], [BENCH-660] Open console link in browser if supported, update start o/p message

gradle/testing.gradle
Test user cleanup gradle task currently failing due to missing version info.
=> PF-2836: cleanupTestUserWorkspaces requires version info

src/main/java/bio/terra/cli/businessobject/User.java, src/main/java/bio/terra/cli/cloud/auth/Oauth.java
Reverts DataBiosphere/terra-cli#511
Cannot use access token for ADC login so I reverted the change to use access token when auth0 is enabled. 
kept the change to not refresh when getting access token.
=> Revert "Revert "PF-2817: When auth0 enabled, use access token and not refresh…"

src/main/java/bio/terra/cli/command/resource/create/AwsSageMakerNotebook.java, src/test/java/unit/AwsS3StorageFolderControlledTest.java, src/test/java/unit/AwsSageMakerNotebookControlledTest.java, src/test/java/unit/GcpNotebookControlled.java, src/test/java/unit/WorkspaceAwsTest.java
- Same as https://github.com/DataBiosphere/terra-cli/pull/513, for AWS notebooks
- remove unused functions
- rename test classes to have suffix 'Test'
=> [PF-2837] Remove access and cloning flags for aws-notebook creation

src/main/java/bio/terra/cli/utils/mount/handlers/GcsFuseMountHandler.java
Currently, when a user mounts a bucket as read only and runs `ls -l` inside the mounted bucket, the files will have incorrect permission bits set. The default 644 (rx-r--r--) set by `gscfuse`. @mbookman proposed using the `--file-mode` and `--dir-mode` flags in `gcsfuse` to set the correct read only file permissions on files and directories. This PR does just that!
=> [PF-2783] Add read only file permission bits

src/test/java/harness/utils/TestUtils.java, src/test/java/unit/AwsS3StorageFolderControlledTest.java, src/test/java/unit/AwsSageMakerNotebookControlledTest.java, src/test/java/unit/DuplicateWorkspaceGcp.java, src/test/java/unit/GcpPassthroughApps.java, src/test/java/unit/WorkspaceAwsTest.java
- add a suitable prefix to AWS resource identifiers created in test scripts
- This helps to separate out test script resources from user created resources for manual cleanup (if needed)
- This applies to - 
- ResourceName (stored in sam)
- for S3 - folderName
- for SageMaker - instanceName
- To keep it easier in WSM tests same resource and folderName (or instanceName) is used. 
Rename util appendRandomNumber to appendRandomString
---
Reference in WSM - 
util function to append random number to a prefix - https://github.com/DataBiosphere/terra-workspace-manager/blob/main/service/src/test/java/bio/terra/workspace/common/fixtures/ControlledAwsResourceFixtures.java#L139
same resource and folderName used - https://github.com/DataBiosphere/terra-workspace-manager/blob/main/service/src/test/java/ …
=> [BENCH-781] User suitable prefix for test AWS resources

src/main/java/bio/terra/cli/businessobject/User.java, src/main/java/bio/terra/cli/cloud/auth/Oauth.java
Even when auth0 is enabled, we use ADC to login to vertex ai notebook so in that case it is still a google credentials. 
currently when opening a vertex ai notebook on startup, we can do all the normal terra operation with the id token. but it will throw NPE when claling terra auth status because the access token is not there. This is because we assume that it is an auth0 login when calling getAccessToken but in the case of vertex ai notebook env, it is actually an ADC id token
=> PF-2913: Distinguish an auth0 token based on whether auth0 is enabled and it is a browser login

src/main/java/bio/terra/cli/businessobject/Workspace.java, src/main/java/bio/terra/cli/command/Folder.java, src/main/java/bio/terra/cli/command/Main.java, src/main/java/bio/terra/cli/command/folder/SetProperty.java, src/main/java/bio/terra/cli/command/folder/Tree.java, src/main/java/bio/terra/cli/command/shared/options/Format.java, src/main/java/bio/terra/cli/serialization/userfacing/UFFolder.java, src/main/java/bio/terra/cli/serialization/userfacing/UFWorkspaceLight.java, src/main/java/bio/terra/cli/service/WorkspaceManagerService.java, src/main/java/bio/terra/cli/utils/PropertiesUtils.java
```
yuhuyoyo-macbookpro2:terra-cli yuhuyoyo$ terra folder tree
└── Data from 1000 Genomes Phase 3(175b1f73-a868-457e-b2ff-4bf95cdc5fa7)
├── BigQuery tables(33d08e65-68df-4d6a-8baa-2567388789db)
└── GCS folders(df48c9b2-820d-49ac-a53e-65a18c0c68c7)
└── Synthetic phenotypes(aa951c12-0051-493f-bf4f-2f8b8de1be02)
yuhuyoyo-macbookpro2:terra-cli yuhuyoyo$ terra folder set-property --id=aa951c12-0051-493f-bf4f-2f8b8de1be02 --properties=foo=bar,k=v
bio.terra.cli.serialization.userfacing.UFFolder@3d24420b
Folder properties successfully updated.
ID:                aa951c12-0051-493f-bf4f-2f8b8de1be02
Name:              Synthetic phenotypes
Description:       null
Parent folder ID:  df48c9b2-820d-49ac-a53e-65a18c0c68c7
Properties:
foo: bar
k: v
```
=> PF-2910: add support for folder in cli command

docker/Dockerfile
see https://broadworkbench.atlassian.net/browse/PF-2924.  
The older pinned version broke (at least) the `terra gcloud artifacts repositories create`  command.
=> [PF-2924] update gcloud version in terra-cli dockerfile

src/main/java/bio/terra/cli/command/workspace/Create.java, src/test/java/harness/utils/WorkspaceUtils.java, src/test/java/unit/Workspace.java
- Allow users to specific spend profile during workspace creation in CLI
- CLI cannot validate spend profile / user’s access to it, since only sam admins can query User manager for user profile with a specific email.
- WSM/ backend will validate spend profile. 
- Assuming that the spend profile is valid and the user has access to it. adding a param to CLI create workspace should let the user specific it as a string (optional).
test - 
```
terra-cli (dexamundsen/profile) >> terra server set --name=verily-devel 
Terra server is set to verily-devel (UNCHANGED).
terra-cli (dexamundsen/profile) >> terra workspace create --id=dex-test-1
Workspace successfully created.
ID:                dex-test-1
Name:              null
Description:       null
Cloud Platform:    GCP
Google project: …
```
=> [BENCH-863] Allow user to specific spend profile during workspace creation

src/test/java/harness/utils/ResourceUtils.java
Similar change was made in WSM - https://github.com/DataBiosphere/terra-workspace-manager/pull/1390
Without this change, AWS notebooks that take 30+ mins for creation will fail in CLI tests (creation + cleanup) and remain as stale resources
=> [BENCH-780] Change resource creation time out to 60 min

src/main/java/bio/terra/cli/businessobject/User.java, src/main/java/bio/terra/cli/cloud/auth/Oauth.java, src/test/java/harness/TestUser.java
the test_user_account json uses google oauth login which is not expecting the offline_access scope. 
put offline_access into the scope at TerraAuthenticationHelper to be closest to when user login to auth0 happens to be most precise.
=> BENCH-966: Revert change to USER_SCOPES to not break tests

src/test/java/unit/GcpNotebookControlled.java
it stays in the provision state for a while so pull till it becomes active
https://scans.gradle.com/s/wgq4l5xlscdlk/tests/task/:runTestsWithTag/details/unit.GcpNotebookControlled/startStop()?top-execution=1
=> BENCH-968: Fix failing gcp notebook test

src/main/java/bio/terra/cli/businessobject/Group.java, src/test/java/unit/Group.java
Currently, several CLI operations log confusing error messages from Sam when a group member tries to do admin-only actions (like listing or modifying a group's membership). We should validate that the user is an admin before making these Sam calls and surface a clearer user-facing exception instead.
=> [PF-2937] Validate group admin role before making Sam calls

src/main/java/bio/terra/cli/cloud/auth/Oauth.java, src/main/java/bio/terra/cli/command/workspace/Create.java, src/main/java/bio/terra/cli/service/FeatureService.java, src/main/java/bio/terra/cli/utils/CommandUtils.java, src/main/resources/servers/verily-autopush.json, src/main/resources/servers/verily-devel.json, src/main/resources/servers/verily-preprod.json, src/main/resources/servers/verily-staging.json, src/main/resources/servers/verily.json
- Create Enums for feature names, defined in FeatureService. This consolidates feature names to a single location
- Util function to use the above feature name enum instead of feature name as string
- Use vwb__aws/gcp_enabled flags instead of reading supported values from server config
- As a fallback for broad server which dont use flagsmith - if feature service returns false, check server config
- Remove supported platforms from server config of verily servers. This enables controlling platform visibility w/o requiring user to re-install newer version of CLI
verily servers (from Flagsmith)
```
>> terra server status
Current server: verily-devel (Verily devel environment)
Server status: OKAY
>> terra workspace create --id=dummy-1
2023-08-30 15:18:47.998 PDT [main] DEBUG …
```
=> [BENCH-1036], [BENCH-1037] Use Flagsmith feature flags for supported platforms

src/main/java/bio/terra/cli/command/workspace/Create.java, src/main/java/bio/terra/cli/utils/CommandUtils.java
Also pass email at flag check in `CommandUtils` instead at the caller level. We should always provide email address for feature flag checks.
=> [BENCH-1067]: Add email address to dataproc flag check

src/main/java/bio/terra/cli/app/CommandRunner.java, src/main/java/bio/terra/cli/businessobject/Resource.java, src/main/java/bio/terra/cli/businessobject/Workspace.java, src/main/java/bio/terra/cli/businessobject/resource/AwsS3StorageFolder.java, src/main/java/bio/terra/cli/businessobject/resource/AwsSageMakerNotebook.java, src/main/java/bio/terra/cli/command/shared/BaseCommand.java, src/main/java/bio/terra/cli/command/workspace/ConfigureAws.java, src/main/java/bio/terra/cli/utils/AwsConfiguration.java, src/main/java/bio/terra/cli/utils/CommandUtils.java, src/main/java/bio/terra/cli/utils/FileUtils.java, src/main/java/bio/terra/cli/utils/mount/MountController.java, src/test/java/harness/baseclasses/ClearContextUnit.java, src/test/java/harness/utils/AwsConfigurationTestUtils.java, src/test/java/unit/WorkspaceAwsTest.java
STATUS
- [done] implementation changes, manual testing
- [done] unit test updates
- Note: changes to flieUtils function needed for config file deletion. 
-----
CHANGES - 
manual configure:
- no change in command and user facing bahavior
- Move implementation from command.execute to AwsConfiguration file 
- Store the config details (such as path, cache etc) as comments in the config file
workspace create:
- Create a empty config file (no resources) with default config values
workspace delete:
- Delete the config file
resource create:
- Load the config from disk, add resource and write back the config file
- No changes to default resource config, since this is automatically added and default must be manually set
resource delete:
- Load the config from disk, delete resource and write back …
=> [BENCH-547] Re-write AWS Config File on Resource Add

src/main/java/bio/terra/cli/businessobject/resource/GcpDataprocCluster.java, src/main/java/bio/terra/cli/command/resource/Update.java, src/main/java/bio/terra/cli/command/resource/create/GcpDataprocCluster.java, src/main/java/bio/terra/cli/command/resource/update/GcpDataprocCluster.java, src/main/java/bio/terra/cli/serialization/userfacing/input/UpdateControlledGcpDataprocClusterParams.java, src/main/java/bio/terra/cli/service/WorkspaceManagerServiceGcp.java, src/test/java/unit/GcpDataprocClusterControlled.java
Adds resource update command for dataproc clusters.
```
❯ terras resource update dataproc-cluster --help
Missing required option: '--name=<name>'
Usage: terra resource update dataproc-cluster
[--autoscaling-policy=<autoscalingPolicy>] [--format=<format>]
[--graceful-decommission-timeout=<gracefulDecommissionTimeout>]
[--idle-delete-ttl=<idleDeleteTtl>] --name=<name>
[--new-description=<newDescription>] [--new-name=<newName>]
[--num-secondary-workers=<numSecondaryWorkers>]
[--num-workers=<numWorkers>] [--workspace=<id>]
Update a GCP Dataproc cluster.
--autoscaling-policy=<autoscalingPolicy>
Autoscaling policy url to attach to the cluster.
Format: projects/[projectId]/locations/
[dataproc_region]/autoscalingPolicies/[policy_id]
--format=<format>      Set the format for printing command …
```
=> [BENCH-1086]: Add terra resource update dataproc-cluster command

.github/workflows/tests-nightly.yml
Comment out the nightly test schedule. Verily is no longer maintaining the code in this repository.
=> Remove nightly test schedule
